### ISSUE TITLE
jackson can't serialize nested object

### ISSUE THREAD

**Issue by zhaozhi406** [spring-projects-experimental/spring-native#1569] opened 2022-04-02 11:51 UTC
I write a simple controller method below:
```
@PostMapping(path = "/buy-goods", consumes = MediaType.APPLICATION_JSON_VALUE)
  public BaseResponse buyGoods(@RequestBody BuyRequest request) {
    BaseResponse response = new BaseResponse(0, "", new BuyResponse(true));
    return response;
  }
```
and `BaseResponse` , `BuyResponse` are definited as below (to make it clear, I removed Lombok annotations)
```
public class BaseResponse {
  private int errno;
  private String errmsg;
  private Object data;

  public BaseResponse(int errno, String errmsg, Object data) {
    this.errno = errno;
    this.errmsg = errmsg;
    this.data = data;
  }

  public BaseResponse() {
  }

  public int getErrno() {
    return errno;
  }

  public void setErrno(int errno) {
    this.errno = errno;
  }

  public String getErrmsg() {
    return errmsg;
  }

  public void setErrmsg(String errmsg) {
    this.errmsg = errmsg;
  }

  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }
}
```
```
public class BuyResponse {
  private boolean success;

  public BuyResponse(boolean success) {
    this.success = success;
  }

  public BuyResponse() {
  }

  public boolean getSuccess() {
    return success;
  }

  public void setSuccess(boolean success) {
    this.success = success;
  }
}
```

I can get the right response when not run as native image, but when run as native, I got exception: 
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.example.demo.response.BuyResponse]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.example.demo.response.BuyResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.example.demo.response.BaseResponse["data"])] with root cause
```

after I disable `SerializationFeature.FAIL_ON_EMPTY_BEANS` in my yaml as below:
```
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
```

I can got success response, but **not correct** (because data is empty):
```
{
  "errno": 0,
  "errmsg": "",
  "data": {}
}
```

can anyone tell why this happen?

by the way, @TypeHint and @SerializationHint seems has no help.

here is my pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.zhaozhi</groupId>
	<artifactId>native-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>native-demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<repackage.classifier/>
		<spring-native.version>0.11.1</spring-native.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.experimental</groupId>
			<artifactId>spring-native</artifactId>
			<version>${spring-native.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.tomcat.embed</groupId>
					<artifactId>tomcat-embed-websocket</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.experimental</groupId>
			<artifactId>tomcat-embed-programmatic</artifactId>
			<version>${tomcat.version}</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.16</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<classifier>${repackage.classifier}</classifier>
					<image>
						<builder>paketobuildpacks/builder:tiny</builder>
						<env>
							<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
						</env>
					</image>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.experimental</groupId>
				<artifactId>spring-aot-maven-plugin</artifactId>
				<version>${spring-native.version}</version>
				<configuration>
					<!-- AOT configuration goes here -->
				</configuration>
				<executions>
					<execution>
						<id>test-generate</id>
						<goals>
							<goal>test-generate</goal>
						</goals>
					</execution>
					<execution>
						<id>generate</id>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<profiles>
		<profile>
			<id>native</id>
			<properties>
				<repackage.classifier>exec</repackage.classifier>
				<native-buildtools.version>0.9.9</native-buildtools.version>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.junit.platform</groupId>
					<artifactId>junit-platform-launcher</artifactId>
					<scope>test</scope>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<version>${native-buildtools.version}</version>
						<extensions>true</extensions>
						<executions>
							<execution>
								<id>test-native</id>
								<phase>test</phase>
								<goals>
									<goal>test</goal>
								</goals>
							</execution>
							<execution>
								<id>build-native</id>
								<phase>package</phase>
								<goals>
									<goal>build</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>

```

**Comment by mhalbritter** [comment] 2022-04-05 08:15
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by zhaozhi406** [comment] 2022-04-06 11:37
> If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

Thank you for your reply. You can download the code from here: https://pan.baidu.com/s/1SVpfm-PION-ATHeaQ0qBHA  and the validation code is: n8ej

After you downloaded the code, you should build it with command: `./mvnw -Pnative -DskipTests package`

**Comment by zhaozhi406** [comment] 2022-04-07 02:43
After I changed the type of data in BaseResponse to `BuyResponse`, the api response can correct serialize the response. I guess jackson in spring native can not serialize Object type??

**Comment by mhalbritter** [comment] 2022-04-07 07:08
Sorry, I don't speak the language the download page is in and I can't find the download button. Can you please upload your sample directly to GitHub so that I can clone it? You can also attach a zip file directly to the issue.

> After I changed the type of data in BaseResponse to BuyResponse, the api response can correct serialize the response. I guess jackson in spring native can not serialize Object type??

I *guess* from your description that GraalVM doesn't include `BuyResponse` in your native-image. This can be fixed by providing a `META-INF/native-image/reflect.json` file which points to your `BuyResponse`, see [this documentation](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/#manual-configuration).

**Comment by zhaozhi406** [comment] 2022-04-07 09:44
> Sorry, I don't speak the language the download page is in and I can't find the download button. Can you please upload your sample directly to GitHub so that I can clone it? You can also attach a zip file directly to the issue.
> 
> > After I changed the type of data in BaseResponse to BuyResponse, the api response can correct serialize the response. I guess jackson in spring native can not serialize Object type??
> 
> I _guess_ from your description that GraalVM doesn't include `BuyResponse` in your native-image. This can be fixed by providing a `META-INF/native-image/reflect.json` file which points to your `BuyResponse`, see [this documentation](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/#manual-configuration).

I upload the zip here.
[native-demo.zip](https://github.com/spring-projects-experimental/spring-native/files/8441666/native-demo.zip)

**Comment by mhalbritter** [comment] 2022-04-07 11:28
Thanks.

The problem is that spring-native generates hints for classes returned by controller methods and follows the chain (via static analysis) to find referenced classes. As your `BaseResponse` uses `Object`, the chain is broken. Changing this to `BuyResponse` restores the chain, that why it works.

You can leave this field an `Object` with this hints:

```json
@TypeHint(types = {
		BaseResponse.class,
		BuyResponse.class
}, access = { TypeAccess.PUBLIC_CONSTRUCTORS, TypeAccess.PUBLIC_METHODS })
```

**Closed by mhalbritter** 2022-04-07 11:28 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by zhaozhi406** [comment] 2022-04-07 12:08
> Thanks.
> 
> The problem is that spring-native generates hints for classes returned by controller methods and follows the chain (via static analysis) to find referenced classes. As your `BaseResponse` uses `Object`, the chain is broken. Changing this to `BuyResponse` restores the chain, that's why it works if you change the field.
> 
> You can leave this field an `Object` with this hints:
> 
> ```
> @TypeHint(types = {
> 		BaseResponse.class,
> 		BuyResponse.class
> }, access = { TypeAccess.PUBLIC_CONSTRUCTORS, TypeAccess.PUBLIC_METHODS })
> ```
> 
> There's nothing we can do at spring-native side here, as we can't find runtime polymorphic JSON serialization.

Thank you very much! It works~
