### ISSUE TITLE
@ConfigurationProperties with @Validated - native build fails when annotations present on a record

### ISSUE THREAD

**Issue by prettymama** [spring-projects-experimental/spring-native#1462] opened 2022-01-22 19:46 UTC
Suppose I have `application.properties` with this line
```
server.port = 8080
```

that I want to map with `@ConfigurationProperties` but instead of a class I place the annotation on a record (which is OK with Spring Boot)
```
@ConfigurationProperties("server")
@Validated
public record ServerConfiguration(@Min(1) int port) {}
```

The AOT processor tries to proxy it and fails as it cannot be done.
```
java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class xxx.ServerConfiguration
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:406)
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:379)
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:276)
        at org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:80)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxy(ConfigurationContributor.java:193)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxies(ConfigurationContributor.java:170)
        at org.springframework.aot.nativex.ConfigurationContributor.processBuildTimeClassProxyRequests(ConfigurationContributor.java:142)
        at org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:74)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
java.lang.IllegalStateException: Problem creating proxy with configuration: org.springframework.aop.framework.ProxyConfiguration@6571616c
        at org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:94)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxy(ConfigurationContributor.java:193)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxies(ConfigurationContributor.java:170)
        at org.springframework.aot.nativex.ConfigurationContributor.processBuildTimeClassProxyRequests(ConfigurationContributor.java:142)
        at org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:74)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class xxx.ServerConfiguration
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:406)
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:379)
        at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:276)
        at org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:80)
        ... 16 more
```

Spring Boot: 2.6.2
Spring Native: 0.11.1
GraalVM: 21.3.0 CE

**Comment by sdeleuze** [comment] 2022-01-31 14:45
Could you please try with:
 - `record` without `@Validated`
 - `class` with `@Validated`
To qualify more precisely the source of the error?

**Comment by prettymama** [comment] 2022-01-31 19:18
`class` with `@Validated` works, I have it currently as a workaround.
`record` without `@Validated` builds and runs OK.

**Comment by prettymama** [comment] 2022-02-04 18:53
I tried some experimentation and it seems that when the configuration is a bit more "complex" (multilayered), configuration values are not bound to properties.

e.g.
Configuration
```
servers:
  server: 
    port: 10001
```

Records:
```
@ConfigurationProperties("servers")
public record ServersConfiguration(ServerConfiguration server) {
  public record ServerConfiguration(int port) {
    public ServerConfiguration{
      System.out.println("Port: " + port);
    }
  }
}
```

In native image the `Port: 10001` is not printed out, in JVM version it's OK.

Removing one layer:
```
server: 
  port: 10001
```
```
@ConfigurationProperties("server")
public record ServerConfiguration(int port) {
  public ServerConfiguration{
    System.out.println("Port: " + port);
  }
}
```
and the line is printed.

**Comment by sdeleuze** [comment] 2022-02-11 09:42
The proxy issue is likely a duplicate of #969, I will create another one for the proper nested record detection.

**Closed by sdeleuze** 2022-02-11 09:42 UTC
Labels: type: bug
