### ISSUE TITLE
Swagger integration issue: Native reflection configuration for springfox.documentation.spi.schema.ModelBuilderPlugin is missing.

### ISSUE THREAD

**Issue by Abhishek150995** [spring-projects-experimental/spring-native#1007] opened 2021-08-31 11:04 UTC
My application failed to start after building native image (upon integrating Swagger in my Sprint Boot Application)
plugins:
        id 'org.springframework.boot' version '2.5.4'
	id 'org.springframework.experimental.aot' version '0.10.3'

dependencies: 
implementation "io.springfox:springfox-swagger2:2.9.2"
implementation "io.springfox:springfox-bean-validators:2.9.2"
implementation "io.springfox:springfox-swagger-ui:2.9.2"

bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    environment = [
        "BP_NATIVE_IMAGE" : "true"
    ]
}

***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for springfox.documentation.spi.schema.ModelBuilderPlugin is missing.

Action:

Native configuration for a class accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.

 
@sdeleuze Please suggest. Thanks in advance

**Comment by sdeleuze** [comment] 2021-09-06 07:18
Duplicate of https://github.com/springfox/springfox/issues/3816, be also aware that https://github.com/springdoc/springdoc-openapi already provide OpenAPI support with Spring Native.

**Closed by sdeleuze** 2021-09-06 07:18 UTC
Labels: status: waiting-for-triage
