### ISSUE TITLE
UnsupportedFeatureError with DecoratingProxy not found

### ISSUE THREAD

**Issue by nekperu15739** [spring-projects-experimental/spring-native#784] opened 2021-05-17 12:27 UTC
Hi, i just build a service that handle a request storing some data on redis for authenticated users.  the source is [here](https://github.com/nekperu15739/anagram) and is throwing the following exception:

`Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface org.springframework.aop.SpringProxy, interface org.springframework.aop.framework.Advised, interface org.springframework.core.DecoratingProxy] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87) ~[na:na]
at com.oracle.svm.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:113) ~[na:na]
at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:66) ~[na:na]
at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006) ~[na:na]
at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:126) ~[na:na]
at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[na:na]
at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:467) ~[com.nekperu15739.anagram.AnagramApplication:5.3.6]
at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:341) ~[com.nekperu15739.anagram.AnagramApplication:5.3.6]
at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:290) ~[com.nekperu15739.anagram.AnagramApplication:5.3.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:437) ~[na:na]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[na:na]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[na:na]
... 16 common frames omitted`

And for future, my question will be, how as developer get a clue to solve the underhood problem?

Kind regards

**Comment by sdeleuze** [comment] 2021-05-17 15:05
After adding `@ProxyHint(types = { SpringProxy.class, Advised.class, DecoratingProxy.class })`, there is a `AnagramHandler` related error. `AnagramHandler` is a class that requires a proxy since it is using `@PreAuthorize`, so this issue is likely a duplicate of #356.

**Closed by sdeleuze** 2021-05-17 15:05 UTC
Labels: status: waiting-for-triage
