### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.graalvm.utils.LiteConfigurationInitializer

### ISSUE THREAD

**Issue by guofengzh** [spring-projects-experimental/spring-native#422] opened 2020-12-20 06:17 UTC
I used 0.8.3 and got the error. I found that 0.8.5 is released, so I tried 0.8.5, but still got the same error.

How to solve it? Your help is appreciated.

This is the url for the pom: https://github.com/guofengzh/service-loader-example-graal/blob/master/service-example/pom.xml

the following is the stacktrace when run service-example.exe:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.graalvm.utils.LiteConfigurationInitializer
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:467)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:449)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:442)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:284)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:264)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
        at sukumaar.SpringBootLoaderApplication.main(SpringBootLoaderApplication.java:11)
Caused by: java.lang.ClassNotFoundException: org.springframework.graalvm.utils.LiteConfigurationInitializer
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1292)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:460)
        ... 7 more
```

**Comment by sdeleuze** [comment] 2021-01-04 16:42
The root cause seems to be that this sample [is not using `@SpringBootApplication` but just `@Configuration`.](https://github.com/guofengzh/service-loader-example-graal/blob/master/service-example/src/main/java/sukumaar/SpringBootLoaderApplication.java#L7), any reason for that?

**Comment by sdeleuze** [comment] 2021-01-05 11:09
I close it for now, we will reopen if needed.

**Comment by sdeleuze** [comment] 2021-01-05 17:27
I currently see this error in `configclient-new` sample which is using `@SpringBootApplication`. Any thoughts on that one @aclement?

**Comment by sdeleuze** [comment] 2021-01-07 15:53
`spring.factories` processing is skipped due to agent mode enabled automatically due to `org.springframework.boot.autoconfigure.SpringBootApplication` present in reflection config, hence this error.

**Closed by sdeleuze** 2021-01-07 15:53 UTC
Labels: type: bug
