### ISSUE TITLE
Class proxy missing at runtime, hint required at build time: @AotProxyHint

### ISSUE THREAD

**Issue by AlSherif** [spring-projects-experimental/spring-native#893] opened 2021-07-06 16:11 UTC
Setup:
Spring Boot 2.5.2
Spring Native: 0.10.1
spring-aot-maven-plugin: 0.10.1
native-maven-plugin: 0.9.0
buildArgs:
`                --verbose
                --enable-http
                --enable-https
                --trace-object-instantiation=sun.nio.ch.Iocp
                --initialize-at-build-time=org.apache.commons.logging.impl.SLF4JLocationAwareLog
                --trace-object-instantiation=sun.nio.ch.WindowsAsynchronousFileChannelImpl
                --initialize-at-build-time=sun.instrument.InstrumentationImpl
                --trace-class-initialization=sun.instrument.InstrumentationImpl
                --trace-class-initialization=org.eclipse.jetty.security.ConstraintSecurityHandler
                --trace-object-instantiation=org.eclipse.jetty.security.ConstraintSecurityHandler
                -H:+ReportExceptionStackTraces`

When starting the generated image I receive the following error message:
`Caused by: java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.berosys.amisconnect.platform.service.datastore.request.RequestDataStoreImpl.class, interfaces={org.springframework.aop.scope.ScopedObject.class, java.io.Serializable.class, org.springframework.aop.framework.AopInfrastructureBean.class})`

I also set up the tracing agent as described in the spring native documentation and ran it to generate additional configuration information.

After adding the cited Annotation(@AotProxyHint...) to the @SpringBootApplication annotated class, nothing changes.
Am I missing something?

**Comment by sdeleuze** [comment] 2021-07-07 09:22
Please provide a repro project.

**Comment by AlSherif** [comment] 2021-07-07 10:26
I will try to create one. 

In general the documentation for the native hints still seems to be lacking a bit.

I have a class RequestDataStoreImpl annotated with
`@Scope(scopeName = "request", proxyMode = ScopedProxyMode.TARGET_CLASS)`

What is the correct approach to identify the correct native hint and parameters?

**Comment by AlSherif** [comment] 2021-07-07 10:51
And another question if I use
```
        <artifactId>spring-aot-maven-plugin</artifactId>
        <version>0.10.1</version>
        <configuration>
          <mode>native-agent</mode>
        </configuration>
```
Do the native hints still get evaluated and merged with the configuration files generated by the tracing agent?

**Comment by sdeleuze** [comment] 2021-07-08 09:47
For scope I will let @aclement answer.

For the tracing agent, yes both configs are taken in account.

**Comment by aclement** [comment] 2021-07-08 21:43
> In general the documentation for the native hints still seems to be lacking a bit.
It is certainly lacking around what to place in the `AotProxyHint`s, due to the intricacies/subteties of how the runtime determines what kinds of proxy to create. The absolute simplest way to work out what AotProxyHints you need is to exercise that runtime code by building and launching a native-image - if they are missing you will be told exactly what they should be (as you found in the original message on this bug report). It isn't ideal but the class proxy hints support is brand new and a work in progress.  The agent will not collect AotProxyHints - build time generated proxies are not used in JVM mode so attaching the agent to JVM mode won't see them.

The intent would be that if you are using typical Spring usage patterns, you don't have to write any hints at all. But until we get further along you are going to find gaps. As per Sebastien comment - if you added the AotProxyHint it suggested and absolutely nothing changed (so you got the same error about exactly the same hint being missing) that is a bug and we need a repro test case, because we've not seen that behaviour before.  If something *different* failed, then it is just more missing config and a simple way to collect most of that is using the agent. I don't typically run the agent myself through maven. I just do (based on https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#_using_the_access_filter_file):

```
java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image/a/b -jar target/myapp.jar
```

I use the a/b folder structure so it doesn't trample on any config you are already manually managing in there but it will be merged with that config (all discovered/computed config is merged) when building the native image.
(This answers your other question - all the config should get merged - the only care to take is that you don't trample on configuration being manually managed by, for example, generating test agent collected config over your manual config)

But that's just how I do things, running agent via the tests should be fine too: https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#tracing-agent-testing.

**Comment by sdeleuze** [comment] 2021-07-19 15:45
@AlSherif Could you please share an updated status and a repro project if needed?

**Comment by sdeleuze** [comment] 2021-07-26 09:56
Closing due to the lack of reproducer.

**Closed by sdeleuze** 2021-07-26 09:56 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage

**Comment by sanjeevsachdev** [comment] 2022-08-12 14:16
> Setup: Spring Boot 2.5.2 Spring Native: 0.10.1 spring-aot-maven-plugin: 0.10.1 native-maven-plugin: 0.9.0 buildArgs: ` --verbose --enable-http --enable-https --trace-object-instantiation=sun.nio.ch.Iocp --initialize-at-build-time=org.apache.commons.logging.impl.SLF4JLocationAwareLog --trace-object-instantiation=sun.nio.ch.WindowsAsynchronousFileChannelImpl --initialize-at-build-time=sun.instrument.InstrumentationImpl --trace-class-initialization=sun.instrument.InstrumentationImpl --trace-class-initialization=org.eclipse.jetty.security.ConstraintSecurityHandler --trace-object-instantiation=org.eclipse.jetty.security.ConstraintSecurityHandler -H:+ReportExceptionStackTraces`
> 
> When starting the generated image I receive the following error message: `Caused by: java.lang.IllegalStateException: Class proxy missing at runtime, hint required at build time: @AotProxyHint(targetClass=com.berosys.amisconnect.platform.service.datastore.request.RequestDataStoreImpl.class, interfaces={org.springframework.aop.scope.ScopedObject.class, java.io.Serializable.class, org.springframework.aop.framework.AopInfrastructureBean.class})`
> 
> I also set up the tracing agent as described in the spring native documentation and ran it to generate additional configuration information.
> 
> After adding the cited Annotation(@AotProxyHint...) to the @SpringBootApplication annotated class, nothing changes. Am I missing something?

In your application, RequestDataStoreImpl must be getting instantiated using the "new" operator rather than using "@Bean" annotation. Because then only RequestDataStoreImpl instance won't have any proxy created for it.
