### ISSUE TITLE
Cleanup hints and type system

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects-experimental/spring-native#526] opened 2021-02-26 09:58 UTC
Could you please make a pass on:
 - [`AotOptions`](https://github.com/spring-projects-experimental/spring-native/blob/master/spring-aot/src/main/java/org/springframework/nativex/AotOptions.java) default values, especially `buildTimePropertiesMatchIfMissing = true`
 - [`@NativeHint` TODO sort out these 3 members](https://github.com/spring-projects-experimental/spring-native/blob/master/spring-native/src/main/java/org/springframework/nativex/hint/NativeHint.java#L82-L94)
 - Reviewing the [rereference documentation ](https://docs.spring.io/spring-native/docs/0.9.0-SNAPSHOT/reference/)
 - Reviewing the [hint Javadoc](https://docs.spring.io/spring-native/docs/0.9.0-SNAPSHOT/api/org/springframework/nativex/hint/package-summary.html)
 - Removing commented code if outdated and more generally reviewing TODOs and making a cleanup pass on https://github.com/spring-projects-experimental/spring-native/tree/master/spring-aot/src/main/java/org/springframework/nativex

**Comment by aclement** [comment] 2021-02-27 06:11
thank you pulling these together in one story, i lose track when i wake up and have emails on 50 issues :)

**Comment by sdeleuze** [comment] 2021-03-01 14:54
@aclement I think I found an interesting issue related to one of the TODOs. If you see [this branch](https://github.com/sdeleuze/spring-native/commit/caching) where I am adding support for caching as part of #465.

Here `@NativeHint(trigger = org.ehcache.Cache.class, types = @TypeHint(types = EhCacheCacheConfiguration.class, access = AccessBits.CONFIGURATION))` translates to `{ "name": "org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration" }` without `allDeclaredFields`, `allDeclaredConstructors` or `allDeclaredMethods`.

I did some debug with branch with `mvnDebug clean package` and I can see that this issue seems to be related to [that codepath ](https://github.com/spring-projects-experimental/spring-native/blob/master/spring-aot/src/main/java/org/springframework/nativex/support/ResourcesHandler.java#L588-L597) where `AccessBits inferredRequiredAccess` is not used.

This is blocking caching support, do you think you could refine that code path?

**Comment by aclement** [comment] 2021-03-01 22:32
- [x] AotOptions reviewed

Checked defaults. Javadoc'd the options for future reference - I've no doubt we'll be deleting some of these soonish, comments hopefully make it easier to understand why they are there.

**Comment by aclement** [comment] 2021-03-01 22:33
- [x] Reviewing the reference documentation

**Comment by aclement** [comment] 2021-03-06 06:51
@sdeleuze I am still fiddling with changes here. I want to make things for consistent, but when I do that some of the 'special cases' we have fall away and we end up with slightly larger images (consistency is good but there is a price to pay).  

But something I wanted to check - are you deliberately choosing to trigger `EhCacheCacheConfiguration` on `org.ehcache.Cache` - I worry that the `ConditionalOnClass` on that config for `net.sf.cache.Cache` isn't being satisfied:
```
@Configuration(proxyBeanMethods = false)
@ConditionalOnClass({ net.sf.ehcache.Cache.class, net.sf.ehcache.EhCacheCacheManager.class })
@ConditionalOnMissingBean(org.springframework.cache.CacheManager.class)
@Conditional({ CacheCondition.class, EhCacheCacheConfiguration.ConfigAvailableCondition.class })
class EhCacheCacheConfiguration { // From Spring Boot 2.4.3 unless I'm mistaken
```
 and the infrastructure is auto demoting your CONFIGURATION bits to just regular CLASS because that condition isn't true for petclinic-jpa with the dependencies that have been added. The only ehcache dependency with your changes (which I've tried to mirror on my version of the project) gives me ehcache 3.9.0 which doesn't contain `net.sf.ehcache.Cache`, that is only in a version 2.10.6 I can see. When I change the petclinic-jpa dependency to 2.10.6 and I change your trigger to net.sf.ehcache.Cache, I see the config in the reflect-config.json as expected (since it all lines up with the ConditionalOnClass):
```
  {
    "name": "org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
```
Happy to believe there is work to do here, but something is looking a bit odd.

**Comment by sdeleuze** [comment] 2021-03-06 21:17
Maybe I mixed Ehcache 2 and 3 trigger and hints, I will double check and comment here.

**Comment by snicoll** [comment] 2021-03-07 11:10
`EhCacheCacheConfiguration` is for EhCache 2 only (`net.sf.ehcache`). There isn't a specific auto-configuration for EhCache 3 as it is a JSR-107 implementation that is covered by `JCacheCacheConfiguration`.

Triggering `EhCacheCacheConfiguration` on `org.ehcache.Cache` is therefore wrong.

**Comment by sdeleuze** [comment] 2021-03-07 17:16
Ok sorry for making you losing your time @aclement, and thanks for clarifying @snicoll, I have adapted the cache hints accordingly.

**Comment by aclement** [comment] 2021-03-08 23:44
more tidyup done. Deleted some unused code, removed some TODOs. Actually fixed `follow` and `extractAttributeNames` to  work (less common fields of NativeHint).

**Comment by aclement** [comment] 2021-03-08 23:57
- Deleted some unused code.
- Sorted out javadoc on NativeHint - within that annotation `follow` is now more consistent and `extractAttributeNames` is actually used.

Gradually moving through some TODOs but making less radical changes as we are close to release.

**Comment by aclement** [comment] 2021-03-09 23:50
I'm done for 0.9.0 - I won't fix anything further than isn't a severe regression or blocking problem.

**Closed by aclement** 2021-03-09 23:50 UTC
Labels: type: task
