### ISSUE TITLE
Fix and improve maintainability of Hibernate Validator support

### ISSUE THREAD

**Issue by leccelecce** [spring-projects-experimental/spring-native#732] opened 2021-04-13 16:07 UTC
I have a Spring WebMVC+Thymeleaf application which uses `@javax.validation.constraints.Min` on a form object. 

```
@NoArgsConstructor
@Data
public class Form implements Serializable {

    // section 1
    @Min(0)
    private BigDecimal salePrice = BigDecimal.ZERO;
...
```

The form is used by a `@Controller` like so:

```
@PostMapping(value = "/update", produces = "application/json")
@ResponseBody
public String update(@Valid @ModelAttribute("form") Form form, BindingResult bindingResult,
...
```

pom.xml includes the Spring Boot validation starter, plus Hibernate Validator as the implementation.

```
 <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId
  </dependency>

  <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
   </dependency>
```

In 0.9.1 this works fine. In the current 0.9.2 snapshot, it builds correctly but fails at runtime request with the following:

```
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception 
[Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForBigDecimal': 
Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForBigDecimal]: 
No default constructor found; nested exception is java.lang.NoSuchMethodException: org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForBigDecimal.<init>()] 
with root cause
java.lang.NoSuchMethodException: org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForBigDecimal.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:314)
        at org.springframework.validation.beanvalidation.SpringConstraintValidatorFactory.getInstance(SpringConstraintValidatorFactory.java:56)
        at org.hibernate.validator.internal.engine.constraintvalidation.ClassBasedValidatorDescriptor.newInstance(ClassBasedValidatorDescriptor.java:84)
        at org.hibernate.validator.internal.engine.constraintvalidation.AbstractConstraintValidatorManagerImpl.createAndInitializeValidator(AbstractConstraintValidatorManagerImpl.java:89)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintValidatorManagerImpl.getInitializedValidator(ConstraintValidatorManagerImpl.java:117)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:136)
        at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:54)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
        at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:109)
        at org.springframework.boot.autoconfigure.validation.ValidatorAdapter.validate(ValidatorAdapter.java:65)
        at org.springframework.validation.DataBinder.validate(DataBinder.java:895)
...
```

I can fix it with a @TypeHint for the Hibernate Validator class, but given this worked fine previously in 0.9.1 I'm not sure if this is supposed to be being picked up by the plugin.

```
@TypeHint(types = {
org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForBigDecimal.class,
org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MinValidatorForInteger.class,
org.hibernate.validator.internal.constraintvalidators.bv.number.bound.MaxValidatorForInteger.class
},
access = AccessBits.FULL_REFLECTION)
```

**Comment by sdeleuze** [comment] 2021-04-13 16:25
Let's check again when #730 will be fixed.

**Comment by leccelecce** [comment] 2021-04-13 16:51
[repro.zip](https://github.com/spring-projects-experimental/spring-native/files/6305376/repro.zip)

Attached is a repro project if it helps. You can run it in Docker, go to localhost:8180 and submit the form and it should error. Change spring.native.version to 0.9.1 and it works fine.

**Comment by sdeleuze** [comment] 2021-04-13 18:33
I am AFK but feel free to test with latest snapshots since #730 has just been fixed.

**Comment by leccelecce** [comment] 2021-04-13 18:38
I've just tried with snapshot 0.9.2-20210413.182352 but no change

**Comment by sdeleuze** [comment] 2021-04-14 08:49
I can't make it work with 0.9.1, could you please share a repro where it works with 0.9.1 but not with 0.9.2-SNAPSHOT?

**Comment by sdeleuze** [comment] 2021-04-14 09:01
I can indeed reproduce it with `0.9.2-SNAPSHOT` and not with `0.9.1`.

**Comment by sdeleuze** [comment] 2021-04-14 09:36
After bisecting this error, it seems to be introduced by 537bb4a7f80ed5746d86d05dc656d127a9d48cda, not sure why yet.

**Comment by sdeleuze** [comment] 2021-04-14 10:08
The only difference I see in the reflection config is as expected an additional `"allDeclaredFields": true` entry for `com.ecv.webapp.Form`. I was suspecting previously it was not fully functional, this is confirmed by the sample that show successful validation when using for example `-6`. So yes it seems we need to had more reflection entries to make Hibernate Validator happy.

**Comment by leccelecce** [comment] 2021-04-14 21:30
Interesting - I will have a look at my sample again tomorrow as I was sure it was working when I wrote it up.

**Closed** 2021-04-15 11:02 UTC
Labels: type: compatibility

**Comment by sdeleuze** [comment] 2021-04-15 11:04
I had to do a pretty extensive rework of our validation support to solve this one in a maintainably way, please test the latest snapshots when the build will be finished and let me know if you find something wrong.

**Comment by leccelecce** [comment] 2021-04-15 16:05
Looks good to me, many thanks and apologies for the confusion on my repro with 0.9.1
