### ISSUE TITLE
 Circular depends-on relationship between 'dataSourceScriptDatabaseInitializer' and 'liquibase'

### ISSUE THREAD

**Issue by estigma88** [spring-projects-experimental/spring-native#1506] opened 2022-02-21 22:23 UTC
I am trying to run an application using Liquibase but I got the following error:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer': Circular depends-on relationship between 'dataSourceScriptDatabaseInitializer' and 'liquibase'
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:317) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[com.example.videoapinative.VideoApiNativeApplicationKt:2.6.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[com.example.videoapinative.VideoApiNativeApplicationKt:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[com.example.videoapinative.VideoApiNativeApplicationKt:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[com.example.videoapinative.VideoApiNativeApplicationKt:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[com.example.videoapinative.VideoApiNativeApplicationKt:2.6.3]
        at com.example.videoapinative.VideoApiNativeApplicationKt.main(VideoApiNativeApplication.kt:13) ~[na:na]

```

If I add the following configuration, the error is gone:

```
spring:
  sql:
    init:
      mode: never
```

Not sure if this is a bug. I attached the demo for the error. 
[video-api-native-bug.zip](https://github.com/spring-projects-experimental/spring-native/files/8112351/video-api-native-bug.zip)

After that, I got the following, which is normal as I don't have any hints for Liquibase:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for liquibase.configuration.LiquibaseConfiguration.<init>() is missing.

```

**Comment by snicoll** [comment] 2022-02-22 07:56
Thanks for the report, this is a duplicate of #1480

**Closed by snicoll** 2022-02-22 07:56 UTC
Labels: status: waiting-for-triage
