### ISSUE TITLE
How does Spring Native handle @ConfigurationProperties?

### ISSUE THREAD

**Issue by gozus19p** [spring-projects-experimental/spring-native#902] opened 2021-07-15 07:47 UTC
Hi,

first of all, thanks for your great work on Spring Native.
I am not understanding resources handling. I searched a lot on the web, but I found no solution.

I configured a configuration class that reads prefixed properties from application.yaml file.

```
// Other imports...

@Component
@Configuration
@EnableConfigurationProperties
@EnableAutoConfiguration
@ConfigurationProperties(prefix = "foo")
@Data
@Slf4j
public class ModuleConfiguration {

    private String bar;

    // Other source code

}
```

My `application.yaml` file:

```
# Other lines...
foo:
  bar: Hello World!
```

I am using Gradle to build and run my native-image, using `gradle nativeRun --no-daemon` command from CLI.
The problem is that after the startup I notice that `bar` String is null, while it should contain `Hello World!` value.

I configured native hints on my entry point, as below:

```
// Imports...

@SpringBootApplication
@EnableMongoAuditing
@NativeHint(
		types = {
				@TypeHint(types = ScopedProxyMode.class),
				@TypeHint(types = API.class, typeNames = "org.apiguardian.api.API$Status"),
				@TypeHint(
						types = ScopedProxyFactoryBean.class,
						methods = {
								@MethodHint(name = "<init>"),
								@MethodHint(name = "setTargetBeanName", parameterTypes = String.class),
								@MethodHint(name = "setBeanFactory", parameterTypes = BeanFactory.class),
								@MethodHint(name = "getObject"),
								@MethodHint(name = "getObjectType"),
								@MethodHint(name = "isSingleton")
						}
				),
				@TypeHint(
						types = CachedDataSourceClients.class,
						fields = @FieldHint(name = "configuration", allowUnsafeAccess = true, allowWrite = true)
				),
				@TypeHint(
						types = ObjectFactoryCreatingFactoryBean.class,
						methods = {
								@MethodHint(name = "<init>"),
								@MethodHint(name = "setTargetBeanName", parameterTypes = String.class),
								@MethodHint(name = "setBeanFactory", parameterTypes = BeanFactory.class),
								@MethodHint(name = "getObject"),
								@MethodHint(name = "getObjectType"),
								@MethodHint(name = "isSingleton")
						}
				),
				@TypeHint(
						types = AuditingEntityCallback.class,
						methods = @MethodHint(name = "<init>", parameterTypes = ObjectFactory.class)
				),
				@TypeHint(
						typeNames = "org.springframework.data.mongodb.config.PersistentEntitiesFactoryBean",
						methods = @MethodHint(name = "<init>", parameterTypes = MappingMongoConverter.class)
				),
				@TypeHint(
						typeNames = "org.springframework.data.mongodb.config.MongoAuditingRegistrar",
						methods = @MethodHint(name = "<init>")
				)
		},
		resources = @ResourceHint(patterns = ".*/resources/.*\\.yaml$")
)
@AotProxyHint(...)
public class MySimpleApp {

	public static void main(String[] args) {
		SpringApplication.run(MySimpleApp.class, args);
	}

}
```

My `application.yaml` file is located in `src/main/resources`, as per default.
I read some documentation. I was wondering if I have to say, in some way, to Spring Native that it has to load the configuration during the startup.
I am struggling with this, I kindly ask you for help.

Dependencies:

```
plugins {
	id 'org.springframework.boot' version '2.5.2'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'org.springframework.experimental.aot' version '0.10.1'
	id 'org.graalvm.buildtools.native' version '0.9.0'
	id 'org.sonarqube' version '3.1.1'
}
```

Thank you in advance for your time, have a nice day!

**Comment by sdeleuze** [comment] 2021-07-27 11:10
It should be handled automatically but we have not tested combining such big amount of annotations on a single class. Could you please start with a simple class annotated with `@ConfigurationProperties(prefix = "foo")` to see if that works (it should). You could then add more annotation step by step to see what breaks the support. When you reach that step please provide a reproducer and we will have a deeper look.

**Comment by spring-projects-issues** [comment] 2021-08-03 11:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-08-10 11:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-08-10 11:12 UTC
Labels: status: waiting-for-triage, status: feedback-reminder, status: waiting-for-feedback
