### ISSUE TITLE
Kotlin R2DBC Custom Repository makes container not starts

### ISSUE THREAD

**Issue by mmuniz75** [spring-projects-experimental/spring-native#735] opened 2021-04-14 13:28 UTC
A Kotlin R2DBC Custom Repository makes container not start. 
Looks like is not able to find the method implementation, if remove the custom repository the regular ones works fine.

The error is :  Failed to create query for method public abstract reactor.core.publisher.Flux edu.muniz.askalien.admin.repository.QuestionCustomizedRepository.findAll(edu.muniz.askalien.admin.repository.QuestionFilter)! No property findAll found for type Question!

The repository implementations are :

```
interface QuestionCustomizedRepository {
    fun findAll(filter: QuestionFilter): Flux<Question>
}

class QuestionRepositoryImpl : QuestionCustomizedRepository {

    @Autowired
    lateinit var databaseClient: DatabaseClient

    override fun findAll(filter: QuestionFilter): Flux<Question> {
	     .....
		return  databaseClient.sql(sql.toString())
				.map(MAPPING_FUNCTION)
				.all()
	}  
}	

interface QuestionRepository : ReactiveCrudRepository<Question, Integer>, QuestionCustomizedRepository{
}
```

Full project in : https://github.com/mmuniz75/native-test/tree/issue2

Full log :
```
Failed to create query for method public abstract reactor.core.publisher.Flux edu.muniz.askalien.admin.repository.QuestionCustomizedRepository.findAll(edu.muniz.askalien.admin.repository.QuestionFilter)! No property findAll found for type Question!
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[na:na]
askalien-admin_1  |     ... 21 common frames omitted
askalien-admin_1  | Caused by: java.lang.IllegalArgumentException: Failed to create query for method public abstract reactor.core.publisher.Flux edu.muniz.askalien.admin.repository.QuestionCustomizedRepository.findAll(edu.muniz.askalien.admin.repository.QuestionFilter)! No property findAll found for type Question!
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.query.PartTreeR2dbcQuery.<init>(PartTreeR2dbcQuery.java:72) ~[na:na]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactory$R2dbcQueryLookupStrategy.resolveQuery(R2dbcRepositoryFactory.java:199) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:100) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(QueryExecutorMethodInterceptor.java:93) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
askalien-admin_1  |     at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
askalien-admin_1  |     at java.util.Collections$UnmodifiableCollection$1.forEachRemaining(Collections.java:1054) ~[na:na]
askalien-admin_1  |     at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:95) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:85) ~[na:na]
askalien-admin_1  |     at java.util.Optional.map(Optional.java:265) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:85) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:303) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[edu.muniz.askalien.admin.AdminApplicationKt:2.4.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.data.util.Lazy.getNullable(Lazy.java:230) ~[na:na]
askalien-admin_1  |     at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[edu.muniz.askalien.admin.AdminApplicationKt:2.4.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.support.R2dbcRepositoryFactoryBean.afterPropertiesSet(R2dbcRepositoryFactoryBean.java:167) ~[edu.muniz.askalien.admin.AdminApplicationKt:1.2.8-SNAPSHOT]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[na:na]
askalien-admin_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[na:na]
askalien-admin_1  |     ... 31 common frames omitted
askalien-admin_1  | Caused by: org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Question!
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90) ~[na:na]
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:437) ~[na:na]
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:413) ~[na:na]
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:366) ~[na:na]
askalien-admin_1  |     at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330) ~[na:na]
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:348) ~[na:na]
askalien-admin_1  |     at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:331) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.Part.<init>(Part.java:81) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.PartTree$OrPart.lambda$new$0(PartTree.java:249) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
askalien-admin_1  |     at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.PartTree$OrPart.<init>(PartTree.java:250) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.PartTree$Predicate.lambda$new$0(PartTree.java:383) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
askalien-admin_1  |     at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
askalien-admin_1  |     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
askalien-admin_1  |     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.PartTree$Predicate.<init>(PartTree.java:384) ~[na:na]
askalien-admin_1  |     at org.springframework.data.repository.query.parser.PartTree.<init>(PartTree.java:92) ~[na:na]
askalien-admin_1  |     at org.springframework.data.r2dbc.repository.query.PartTreeR2dbcQuery.<init>(PartTreeR2dbcQuery.java:68) ~[na:na]
askalien-admin_1  |     ... 55 common frames omitted
```

**Comment by sdeleuze** [comment] 2021-04-14 14:06
Hi, yeah that's a known issue, and probably a duplicate of #643.

**Closed by sdeleuze** 2021-04-14 14:06 UTC
Labels: status: waiting-for-triage
