### ISSUE TITLE
Cannot enable Tomcat MBeans in JVM mode

### ISSUE THREAD

**Issue by shakuzen** [spring-projects-experimental/spring-native#805] opened 2021-06-03 08:57 UTC
I was trying to do a comparison of metrics that would be available when running on the JVM vs as a native image. Unfortunately, when running the application on the JVM I could not enable the [Tomcat metrics Spring Boot configures](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.tomcat) with this property is set: `server.tomcat.mbeanregistry.enabled=true`. It seems the Tomcat MBeans do not get registered. If I remove the `spring-native` dependency, the MBeans will be registered as expected.

This is with generating a new project from Spring Initializr using Spring Boot 2.5.0 and Spring Native 0.10.0-SNAPSHOT. I generated the project with web, actuator, prometheus, and spring-native dependencies.

**Comment by sdeleuze** [comment] 2021-06-03 13:01
@aclement It seems [JMX autoconfig are discarded](https://github.com/spring-projects-experimental/spring-native/blob/main/spring-aot/src/main/java/org/springframework/aot/factories/AutoConfigurationFactoriesCodeContributor.java#L89-L95) regardless of the status of `removeJmxSupport`. Any thoughts?

**Comment by aclement** [comment] 2021-06-03 23:58
Yeah, I think that up front check doesn't match the related check happening later in [ResourcesHandler](https://github.com/spring-projects-experimental/spring-native/blob/f5027c67e7df0744c022bf11ee237b43b268d9ef/spring-aot/src/main/java/org/springframework/nativex/support/ResourcesHandler.java#L1065).

I fixed it up and confirmed as best I can without a test case. Without the change there were no JMX related entries in the generated spring factories code, with the change there are 3 (this is the actuator-webmvc sample which seemed close to the description):
```
-> grep -ri jmx target/generated-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java
target/generated-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java:    names.add(EnableAutoConfiguration.class, "org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration");
target/generated-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java:    names.add(EnableAutoConfiguration.class, "org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration");
target/generated-sources/spring-aot/src/main/java/org/springframework/aot/StaticSpringFactories.java:    names.add(EnableAutoConfiguration.class, "org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration");
```

**Comment by aclement** [comment] 2021-06-03 23:59
@shakuzen can you try it out again?

**Comment by shakuzen** [comment] 2021-07-01 07:00
I've tried with 0.10.1 on my own sample and I tried with the `main` branch of this repo and the actuator-webmvc sample, adding `server.tomcat.mbeanregistry.enabled=true` to `application.properties`. You can see the difference by running the sample with the `spring-boot:run` vs `spring-boot:build-image` and `docker-compose up`. Compare what is available in the localhost:8080/actuator/prometheus endpoint. The former has some `tomcat_` metrics and the latter has none still.

Though even with `spring-boot:run`, there are none of the JMX-based tomcat metrics - only the Tomcat session metrics derived from the Tomcat `Manager` object.

> Without the change there were no JMX related entries in the generated spring factories code, with the change there are 3 (this is the actuator-webmvc sample which seemed close to the description)

Those are related to JMX things Spring Boot creates - Actuator endpoints via JMX, Spring Boot MBean. For the Tomcat mbeans, they are disabled by default unless `server.tomcat.mbeanregistry.enabled=true`. See https://github.com/spring-projects/spring-boot/blob/32a1644cca312d35dbd5d400f5e908a9e8a5a3b6/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/tomcat/TomcatServletWebServerFactory.java#L182-L184

**Comment by shakuzen** [comment] 2021-07-01 07:14
For comparison, if I generate a Spring Boot app from initializr without spring-native and with web, actuator, prometheus, and I add to application.properties:

```properties
management.endpoints.web.exposure.include=*
server.tomcat.mbeanregistry.enabled=true
```

I will see in the prometheus endpoint Tomcat metrics from the mbeans it registers such as:
```
tomcat_threads_config_max_threads{name="http-nio-8080",} 200.0
```

**Comment by sdeleuze** [comment] 2021-07-01 14:51
Just to be sure before testing myself, could you confirm on native you set `removeJmxSupport` to `false` in Spring AOT plugin config since [it is removed by default](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#spring-aot-configuration)?

**Comment by shakuzen** [comment] 2021-07-02 01:08
Yes, I should have mentioned, I added the following to the spring-aot-maven-plugin.
```xml
<configuration>
	<removeJmxSupport>false</removeJmxSupport>
</configuration>
```

**Comment by aclement** [comment] 2021-07-06 02:03
A key thing to recognize here is that the JVM operation of the application breaks once the `spring-native` dependency is included, don't have to even attempt building a native image. That is because it contains a `spring.factories` file that pulls in the `NativeListener`:
```
	static {
		if (!NativeDetector.inNativeImage()) {
			System.setProperty("org.graalvm.nativeimage.imagecode", "runtime");
		}
		...
```
The `setProperty` call there breaks the appearance of the `tomcat_threads_config_max_threads` entry. If I comment out that line and rebuild the app (just `mvn clean package`, no native image building) the `tomcat_threads...` line is there in the actuator output.

**Comment by sdeleuze** [comment] 2021-07-07 06:50
@shakuzen cc @markt-asf This probably needs to be fixed on Tomcat side where [the MBean registry is disabled on native](https://github.com/apache/tomcat/blob/main/java/org/apache/tomcat/util/modeler/Registry.java#L139-L143):

```
if (JreCompat.isGraalAvailable()) {
    disableRegistry();
} else {
    registry = new Registry();
}
```

This is probably a too aggressive optimization or something which was done when MBeans support was broken on native. It would be nice to keep to possibility to disable the MBeans support but using another trigger than the native flag.

Please comment here with the reference of the Tomcat issue when created.

**Closed by sdeleuze** 2021-07-07 06:50 UTC
Labels: type: bug

**Comment by markt-asf** [comment] 2021-07-14 17:15
@sdeleuze 
To be clear, you are asking for
```
if (JreCompat.isGraalAvailable()) {
    disableRegistry();
} else {
    registry = new Registry();
}
```
to be replaced with
```
registry = new Registry();
```
on the basis that Graal Native is now able to support JMX?

**Comment by sdeleuze** [comment] 2021-07-27 10:36
@markt-asf Based on my tests, it works on native but adds `1M` footprint, so it could work as a default, but I was wondering if there is a flag in Tomcat that controls JMX activation? If there is, I could probably provide guidance to make sure native remove the related classes when JMX is disable.

**Comment by markt-asf** [comment] 2021-07-27 11:48
There is a start-up flag but I don't think that will help as you aren't starting Tomcat via the scripts. You can disable JMX (SpringBoot does this by default so there may be a flag you can set there) by calling `org.apache.tomcat.util.modeler.Registry.disableRegistry()`.
I'll update Tomcat as described above for the next round of releases (due early next month).
