### ISSUE TITLE
Cannot make custom validator working

### ISSUE THREAD

**Issue by bojanv55** [spring-projects-experimental/spring-native#1300] opened 2021-11-25 00:03 UTC
I'm using latest spring boot/native/graalvm (made project with https://start.spring.io/, and selected lombok+native+validation). Trying to run this code sample:

```
package com.example.validdemo;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.validation.Constraint;
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import javax.validation.Payload;
import javax.validation.ReportAsSingleViolation;
import javax.validation.Validator;
import javax.validation.constraints.NotEmpty;
import lombok.RequiredArgsConstructor;
import lombok.Value;
import org.hibernate.validator.constraints.Length;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

@SpringBootApplication
public class ValidDemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(ValidDemoApplication.class, args);
	}

}

@Component
class LicenseService {

	public boolean validate(String license) {
		return "123".equals(license);
	}
}

@RequiredArgsConstructor
@Component
class LicenseValidator implements ConstraintValidator<ValidLicense, String> {

	private final LicenseService service;

	@Override
	public boolean isValid(String license, ConstraintValidatorContext constraintValidatorContext) {
		return service.validate(license);
	}
}

@ReportAsSingleViolation
//takes the message of message() method and not `@NotEmpty.message + @Length.message`
@NotEmpty
@Length(min = 3, max = 3)
@Constraint(validatedBy = LicenseValidator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD })
@interface ValidLicense {
	String message() default "activation key is not valid";
	Class<?>[] groups() default {};
	Class<? extends Payload>[] payload() default{};
}

@Value
class SomeDto {
	@ValidLicense
	String license;
}

@RequiredArgsConstructor
@Component
class Runner implements CommandLineRunner {

	private final Validator validator;

	@Override
	public void run(String... args) {
		System.out.println(validator.validate(new SomeDto("abc")));
		System.out.println(validator.validate(new SomeDto("123")));
	}
}
```

If run normally (not native-compiled), I get expected output:

```
[ConstraintViolationImpl{interpolatedMessage='activation key is not valid', propertyPath=license, rootBeanClass=class com.example.validdemo.SomeDto, messageTemplate='activation key is not valid'}]
[]
```

If I compile it, and run, I get:

```
[]
[]
```

and I guess it does not recognize and register validator at all...

Then, I run `native-image-agent` and copied it's generated config to the project. After compilation, this is what I get:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Native reflection configuration for com.example.validdemo.LicenseValidator.<init>() is missing.

Action:

Native configuration for a method accessed reflectively is likely missing.
You can try to configure native hints in order to specify it explicitly.
See https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#native-hints for more details.
```

And I can see this in the config (among a lot of other things):

```
{
  "name":"com.example.validdemo.LicenseService",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[{"name":"<init>","parameterTypes":[] }]}
,
{
  "name":"com.example.validdemo.LicenseValidator",
  "allDeclaredFields":true,
  "queryAllDeclaredMethods":true,
  "queryAllDeclaredConstructors":true,
  "methods":[{"name":"<init>","parameterTypes":["com.example.validdemo.LicenseService"] }],
  "queriedMethods":[{"name":"isValid","parameterTypes":["java.lang.Object","javax.validation.ConstraintValidatorContext"] }]}
```

Is there something more needed here? Is it that I do not have empty constructor and use lombok?

**Comment by sdeleuze** [comment] 2021-11-25 07:10
We probably need to add special handing for constructs like `@Constraint(validatedBy = LicenseValidator.class)`.

**Comment by sdeleuze** [comment] 2021-11-25 07:11
In fact that's a duplicate of #783.

**Closed by sdeleuze** 2021-11-25 07:11 UTC
Labels: type: compatibility

**Comment by bojanv55** [comment] 2021-11-25 08:52
Is there anything I could do now, to make this work?

**Comment by bojanv55** [comment] 2021-11-25 12:49
I think the problem in this code:

```
@RequiredArgsConstructor
@Component
class LicenseValidator implements ConstraintValidator<ValidLicense, String> {

	private final LicenseService service;

	@Override
	public boolean isValid(String license, ConstraintValidatorContext constraintValidatorContext) {
		return service.validate(license);
	}
}
```

Is that there is no default constructor? But again, this should not be the problem, since it is working OK if I run it normally (without native-image-compilation).

This code is working, but it is not good, since we have hard wired dependency in the code:

```
@RequiredArgsConstructor
@Component
class LicenseValidator implements ConstraintValidator<ValidLicense, String> {

	private final LicenseService service;
	
	public LicenseValidator(){
		service = new LicenseService(); //NOT OK - HARD WIRING OF THE DEPENDENCY
	}

	@Override
	public boolean isValid(String license, ConstraintValidatorContext constraintValidatorContext) {
		return service.validate(license);
	}
}
```

This one has default constructor, but it is actually not injecting the bean - I get null pointer exception in the runtime:

```
@Component
class LicenseValidator implements ConstraintValidator<ValidLicense, String> {

	private LicenseService service; //seems setService is never called and we get java.lang.NullPointerException: null

	@Autowired
	public void setService(LicenseService service) {
		this.service = service;
	}

	public LicenseValidator(){
	}

	@Override
	public boolean isValid(String license, ConstraintValidatorContext constraintValidatorContext) {
		return service.validate(license);
	}
}
```

So again, seems easy to make Validator work, but it is problem when I want to inject the bean inside.

**Comment by bojanv55** [comment] 2021-11-25 16:40
This one also works in spring-native (but still, not good solution):

```
@Component
class StaticContextAccessor {

	private static ApplicationContext context;

	@Autowired
	public StaticContextAccessor(ApplicationContext applicationContext) {
		context = applicationContext;
	}

	public static <T> T getBean(Class<T> clazz) {
		return context.getBean(clazz);
	}
}

@Component
class LicenseValidator implements ConstraintValidator<ValidLicense, String> {
	@Override
	public boolean isValid(String license, ConstraintValidatorContext constraintValidatorContext) {
                //manually get bean from static method
		return StaticContextAccessor.getBean(LicenseService.class).validate(license);
	}
}
```

**Comment by bojanv55** [comment] 2021-11-30 10:15
@sdeleuze Are you sure this is duplicate? Seems that spring `@Autowire` is not working here, so not sure that is exactly the same problem as in other issue?

**Comment by sdeleuze** [comment] 2021-12-06 07:34
We will use your repro to validate it works as part of #783.
