### ISSUE TITLE
Support for multi module projects

### ISSUE THREAD

**Issue by MarcelCoding** [spring-projects-experimental/spring-native#551] opened 2021-03-03 14:12 UTC
When I create a project with multiple modules, only the classes in the "main" project are compiled ahead of time. But I cannot add the `org.springframework.experimental.aot` plugin to a library project because it requires the spring boot plugin. When I add the spring boot plugin, the generated jar becomes a bootable jar which includes all dependencies.

**Comment by bclozel** [comment] 2021-03-03 16:41
Hello @MarcelCoding 

I'm not sure I understand the problem here. What would be the expected behavior when the plug-in is applied on a module that's not a Spring Boot application?

**Comment by MarcelCoding** [comment] 2021-03-03 17:49
I have a Grade Project with one common lib and tow spring boot applications. And the common lib is not compiled ahead of time.
This causes that all beans, controller, ... are not recognized by the application. (I updated my Issue "advance" to "ahead of time")

**Comment by bclozel** [comment] 2021-03-03 17:53
The common library should be on the runtime classpath of the Spring Boot applications and taken into account there.
There should be no need to apply that plugin on a per-module basis, but just on the actual Spring Boot application.

Could you create a sample application showing the problem?
Thanks!

**Comment by MarcelCoding** [comment] 2021-03-03 19:15
I created a small spring boot application, which has a local module as dependency.
-> https://github.com/MarcelCoding/spring-native-multi-module

**Comment by MarcelCoding** [comment] 2021-03-04 11:32
This same problem also for jpa entities.

**Comment by bclozel** [comment] 2021-03-04 13:09
There are several issues here.

## Beans present in dependencies

Running the native application, once compiled, fails with the following:

```
2021-03-04 12:57:00.880  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-04 12:57:00.880 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springNativeExampleApplication': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.marcelcoding.spring.library.TestService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

The required component is present in the "library" module, which is not covered by the AOT plugin. The AOT plugin automatically applies the context-indexer to the "application" module, but the "library" module is not covered.

Adding the following to the "library" `build.gradle` solves this first problem.

```
annotationProcessor "org.springframework:spring-context-indexer:5.3.4"
```
@sdeleuze @snicoll What's the general recommendation for the context indexer in this case? In this case, we can manually apply this annotation processor to the "library", but this wouldn't work if this would be a regular dependency. Should we replicate what the indexer is doing at the ASM level?

## Missing server factory

Once this first issue solved, I'm getting the following error:

```
2021-03-04 13:01:26.646  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
2021-03-04 13:01:26.647 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:81) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:576) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:63) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[com.github.marcelcoding.spring.SpringNativeExampleApplication:2.4.3]
	at com.github.marcelcoding.spring.SpringNativeExampleApplication.main(SpringNativeExampleApplication.java:18) ~[na:na]
Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactoryBeanName(ReactiveWebServerApplicationContext.java:107) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:89) ~[na:na]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:78) ~[na:na]
	... 9 common frames omitted
```

We need to figure this one out as well.

Thanks for the sample @MarcelCoding , this is super useful. We'll probably close this issue and spawn new ones once we've uncovered all the problems shown by your sample.

**Comment by sdeleuze** [comment] 2021-03-04 13:34
Interesting. Our goal is to make component indexing part of the AOT process without explicitly declare the dependency so while for now (0.9.0) we can probably add documentation for adding the related dependency when building libraries I tend to think being able to implement it with ASM as a Spring AOT transformation indeed makes sense for consistency and flexibility (compatible with libraries not providing an index).

**Comment by MarcelCoding** [comment] 2021-03-04 13:51
@bclozel Thank you for your reply. I actually didn't realize there were two separate annotation processors. I always thought that the one I had used did all those things.
Should I add that to my example. I can create a separate branch for each of the different variants, after all.

**Comment by snicoll** [comment] 2021-03-05 15:58
The context indexer is fairly limited. Because it is an on/off switch, it has to be applied to every modules whenever it is used.

I understand that it is a requirement of Spring Native so we should make it very clear in the documentation that it must be applied to any module that contributes beans using classpath scanning. IMO, it would be better if its behaviour was replicated directly by the AOT plugin but I have no idea how easy this could be.

**Comment by aclement** [comment] 2021-03-05 22:09
@snicoll @sdeleuze I'll mention I did add that a while ago when I was annoyed when things failed without a reminder to add the indexer. The configuration analyzer/collector that plugs into the AOT plugin will synthesize and store a `spring.components` file if there isn't one. If I build `commandlinerunner` from master right now you will see a synthesized index:
```
target/generated-sources/spring-aot/src/main/resources/META-INF/spring.components
```
which is then copied into `target/classes/META-INF` during the build.

If the project was using `spring-context-indexer` as a dependency then there will not be one in the `generated-sources` folder. 

So what's going here? Is the synthesizer making a mistake or is something different in a multi module setup that needs a more nuanced approach to creating it?

I could imagine right now there is a problem if some modules used the indexer dependency and some didn't. If the build finds any, it won't synthesize one. But if 3 of 4 modules have one and the final module is missing one, we would not notice and so we'd miss components in that 4th module. (I'm just thinking out loud here).

**Comment by aclement** [comment] 2021-03-06 00:09
I have fixed this, or at least the problem I saw:
```
docker run --rm -p 8080:8080 application:1.0-SNAPSHOT
2021-03-06 00:03:17.296  INFO 1 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.3)

2021-03-06 00:03:17.297  INFO 1 --- [           main] c.g.m.s.SpringNativeExampleApplication   : Starting SpringNativeExampleApplication using Java 11.0.10 on bbebb88e77f9 with PID 1 (/workspace/com.github.marcelcoding.spring.SpringNativeExampleApplication started by cnb in /workspace)
2021-03-06 00:03:17.297  INFO 1 --- [           main] c.g.m.s.SpringNativeExampleApplication   : No active profile set, falling back to default profiles: default
2021-03-06 00:03:17.329  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
2021-03-06 00:03:17.329  INFO 1 --- [           main] c.g.m.s.SpringNativeExampleApplication   : Started SpringNativeExampleApplication in 0.037 seconds (JVM running for 0.038)
Hello World
```
The reason for the problems is that although we have `spring.components` synthesis it is a little tightly scoped to avoid scanning too many things. The way the dependant library jar was being passed on the classpath caused it not to be scanned. I included support for this style and it sprang to life.  Synthesis only needed to run on the application project.

**Closed** 2021-03-09 11:57 UTC
Labels: type: bug
