### ISSUE TITLE
error while loading shared libraries: libfreetype.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ojaynico** [spring-projects-experimental/spring-native#1540] opened 2022-03-24 15:47 UTC
I get the error above while trying to run a compiled native file on Ubuntu.

**Comment by sdeleuze** [comment] 2022-03-25 07:27
Please provide a repro project.

**Comment by ojaynico** [comment] 2022-03-25 08:52
I have extracted a project from one of my services that throws the error.

https://github.com/ojaynico/quiz-service

**Comment by sdeleuze** [comment] 2022-03-28 07:27
I can't reproduce on my OS (Archlinux), I guess your Ubuntu installation just miss this library which is needed for some native apps, so I would advise to install it in your system. I am closing this issue since I don't see any actionable item on our side.

**Closed by sdeleuze** 2022-03-28 07:27 UTC
Labels: status: waiting-for-triage, status: feedback-provided
