### ISSUE TITLE
spring-boot-starter-hateoas integration issue

### ISSUE THREAD

**Issue by guenichone** [spring-projects-experimental/spring-native#1056] opened 2021-09-21 20:40 UTC
Hello,

I'm trying to migrate my project to spring native, I already resolved some compatibility issues, but there is one that I cannot figure out.

I'm using :

- Maven 3.6.3
- Adopt-OpenJDK 11.0.9.1+1
- Spring Boot 2.5.4
- Spring Native 0.10.3
- Spring Aot Maven Plugin 0.10.3

Issue happen only when I add the spring-boot-starter-hateoas (or the spring-hateoas dependency), I'm using it to only parse a single LINK header in a remote call.

But when I run install on my project I got the following error, it tries to proxy the String.class :

[INFO] Generating class file bytes for a proxy named java.lang.String$$SpringProxy$4916742f
[INFO] Unable to proxy method [byte[] java.lang.String.value()] because it is package-visible across different ClassLoaders: All calls to this method via a proxy will NOT be routed to the target instance.
[INFO] Unable to proxy method [byte java.lang.String.coder()] because it is package-visible across different ClassLoaders: All calls to this method via a proxy will NOT be routed to the target instance.
[INFO] Unable to proxy method [void java.lang.String.getBytes(byte[],int,byte)] because it is package-visible across different ClassLoaders: All calls to this method via a proxy will NOT be routed to the target instance.
[ERROR] java.lang.IllegalStateException: Problem creating proxy with configuration: org.springframework.aop.framework.ProxyConfiguration@4916742f
[ERROR] [org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:94), org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxy(ConfigurationContributor.java:182), org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxies(ConfigurationContributor.java:160), org.springframework.aot.nativex.ConfigurationContributor.processBuildTimeClassProxyRequests(ConfigurationContributor.java:137), org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:72), org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:77), org.springframework.aot.maven.GenerateMojo.execute(GenerateMojo.java:65), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81), org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56), org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192), org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105), org.apache.maven.cli.MavenCli.execute(MavenCli.java:957), org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289), org.apache.maven.cli.MavenCli.main(MavenCli.java:193), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282), org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225), org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406), org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347), org.codehaus.classworlds.Launcher.main(Launcher.java:47)]
java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class java.lang.String
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:406)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:379)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:276)
	at org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:80)
	at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxy(ConfigurationContributor.java:182)
	at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxies(ConfigurationContributor.java:160)
	at org.springframework.aot.nativex.ConfigurationContributor.processBuildTimeClassProxyRequests(ConfigurationContributor.java:137)
	at org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:72)
	at org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:77)
	at org.springframework.aot.maven.GenerateMojo.execute(GenerateMojo.java:65)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

I don't know why, I checked the sample project with hateoas, and there is no error anymore if I simple remove the hateoas dependency.

Could you help me based on this or should I really try to make the simpliest project possible to reproduce ?

Thank you !

**Comment by sdeleuze** [comment] 2021-09-24 08:53
Please provide a repro project and we will have a look.

**Comment by sdeleuze** [comment] 2021-09-24 08:55
Could be a duplicate of #1038.

**Comment by guenichone** [comment] 2021-09-24 10:18
I had this one too but I fixed this error by replacing the void with an empty ResponseEntity. I will try to create a very simple case to reproduce the issue.

**Comment by sdeleuze** [comment] 2021-09-28 07:24
Ok so I think it is a duplicate of #1038.

**Closed by sdeleuze** 2021-09-28 07:24 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by guenichone** [comment] 2021-09-28 12:15
Hello,

I took time to reproduce a simple case, issue is not directly related to hateoas, but hateoas WITH springdoc open api ui.

You can find a simple repository to reproduce the issue 👍 

https://github.com/guenichone/spring-native

Thank you 😊
