### ISSUE TITLE
Runtime Error: java.lang.NoSuchMethodException: org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$EmptyHandler.handle()

### ISSUE THREAD

**Issue by salvob** [spring-projects-experimental/spring-native#1510] opened 2022-02-24 22:27 UTC
Hi, I have runtime error when compile with arg --language:js

GraalVm version 22.0.0.2 graalvm-ce-java17-darwin-amd64

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping': Unexpected exception during bean creation; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[api:2.6.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[api:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[api:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[api:2.6.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[api:2.6.1]
        at com.epipoli.HwApplication.main(HwApplication.java:55) ~[api:0.0.1]
Caused by: java.lang.ExceptionInInitializerError: null
        at java.lang.Class.ensureInitialized(DynamicHub.java:549) ~[api:na]
        at java.lang.Class.ensureInitialized(DynamicHub.java:549) ~[api:na]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.createRequestMappingHandlerMapping(WebMvcConfigurationSupport.java:351) ~[api:5.3.13]
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.createRequestMappingHandlerMapping(WebMvcAutoConfiguration.java:543) ~[api:2.6.1]
        at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerMapping(WebMvcConfigurationSupport.java:311) ~[api:5.3.13]
        at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.requestMappingHandlerMapping(WebMvcAutoConfiguration.java:445) ~[api:2.6.1]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$24(ContextBootstrapInitializer.java:244) ~[na:na]
        at org.springframework.aot.beans.factory.ThrowableFunction.apply(ThrowableFunction.java:18) ~[na:na]
        at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:51) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$InstanceSupplierContext.create(BeanDefinitionRegistrar.java:193) ~[na:na]
        at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$25(ContextBootstrapInitializer.java:244) ~[na:na]
        at org.springframework.aot.beans.factory.ThrowableFunction.apply(ThrowableFunction.java:18) ~[na:na]
        at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:97) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
        ... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$EmptyHandler.handle()
        at org.springframework.util.ClassUtils.getMethod(ClassUtils.java:1141) ~[na:na]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.<clinit>(AbstractHandlerMethodMapping.java:84) ~[na:na]
        ... 31 common frames omitted`

**Comment by sdeleuze** [comment] 2022-03-03 10:01
Please share a repro project.

**Comment by LilPoppy** [comment] 2022-03-15 06:45
I have a same issue with `OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)`

```
2022-03-15 01:39:38.573 ERROR 39550 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping': Unexpected exception during bean creation; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:555) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[na:na]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[na:na]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[na:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[na:na]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[cobnet:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[cobnet:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[cobnet:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[cobnet:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[cobnet:2.6.4]
	at com.cobnet.EntryPoint.main(EntryPoint.java:77) ~[cobnet:0.0.1-SNAPSHOT]
Caused by: java.lang.ExceptionInInitializerError: null
	at java.lang.Class.ensureInitialized(DynamicHub.java:510) ~[cobnet:na]
	at java.lang.Class.ensureInitialized(DynamicHub.java:510) ~[cobnet:na]
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.createRequestMappingHandlerMapping(WebMvcConfigurationSupport.java:351) ~[cobnet:5.3.16]
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.createRequestMappingHandlerMapping(WebMvcAutoConfiguration.java:543) ~[cobnet:2.6.4]
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerMapping(WebMvcConfigurationSupport.java:311) ~[cobnet:5.3.16]
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.requestMappingHandlerMapping(WebMvcAutoConfiguration.java:445) ~[cobnet:2.6.4]
	at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$24(ContextBootstrapInitializer.java:399) ~[na:na]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedElementResolver.create(InjectedElementResolver.java:67) ~[na:na]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$BeanInstanceContext.create(BeanDefinitionRegistrar.java:211) ~[na:na]
	at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$25(ContextBootstrapInitializer.java:399) ~[na:na]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar$ThrowableFunction.apply(BeanDefinitionRegistrar.java:294) ~[na:na]
	at org.springframework.aot.beans.factory.BeanDefinitionRegistrar.lambda$instanceSupplier$0(BeanDefinitionRegistrar.java:115) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1249) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[na:na]
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$EmptyHandler.handle()
	at org.springframework.util.ClassUtils.getMethod(ClassUtils.java:1141) ~[na:na]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.<clinit>(AbstractHandlerMethodMapping.java:84) ~[cobnet:5.3.16]
	... 31 common frames omitted
```

Seen this exception is which method not found , I have attempt to add the below into my `reflect-config.json `. But still it's not working.

```
 {
    "name":"org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.EmptyHandler",
    "methods":[{ "name":"<init>","parameterTypes":[] } , { "name": "handle", "parameterTypes": [] }],
    "queryAllDeclaredMethods": true
  }
```

**Comment by sdeleuze** [comment] 2022-03-15 09:26
@LilPoppy Could you please provide a repro project?

**Comment by LilPoppy** [comment] 2022-03-16 06:49
> repro project?

Sure, here is the [repository](https://github.com/SpamanDev/StoreChain-Server) with [CI](https://github.com/SpamanDev/StoreChain-Server/actions/runs/1991171864)

**Comment by sdeleuze** [comment] 2022-03-18 09:26
Sorry the setup to reproduce is not obvious, I followed readme instructions and the build is broken due to the database. Could you please provide a more focused repro with complete instructions to reproduce?

**Comment by LilPoppy** [comment] 2022-03-18 10:11
> Sorry the setup to reproduce is not obvious, I followed readme instructions and the build is broken due to the database. Could you please provide a more focused repro with complete instructions to reproduce?

Hi @sdeleuze , You should [config](https://github.com/SpamanDev/StoreChain-Server/blob/f765b46f9aa2086c00baab99517b56ccdb33afcf/pom.xml#L19) a bit for your environment.

**Comment by LilPoppy** [comment] 2022-03-18 16:50
Hi @sdeleuze , I have found out some other issues from GraalVM and have them commented.

1. No supported [Datasource](https://github.com/SpamanDev/StoreChain-Server/blob/ee0204a8b26e54efccb4eb8abd2bf9d3ae7ef51a/src/main/java/com/cobnet/spring/boot/configuration/DatasourceConfiguration.java#L33) type found.
2. [@EnableRedisHttpSession](url) will cause: Cannot invoke "org.springframework.util.StringValueResolver.resolveStringValue(String)" because "this.embeddedValueResolver" is null
3. [Context.create()](https://github.com/SpamanDev/StoreChain-Server/blob/ee0204a8b26e54efccb4eb8abd2bf9d3ae7ef51a/src/test/java/com/cobnet/test/SpringApplicationTests.java#L40) java.lang.NullPointerException: Cannot invoke "com.oracle.truffle.api.impl.TVMCI.createRuntimeSupport(Object)"
4. [AuthenticationManager](https://github.com/SpamanDev/StoreChain-Server/blob/ee0204a8b26e54efccb4eb8abd2bf9d3ae7ef51a/src/main/java/com/cobnet/spring/boot/configuration/SecurityConfiguration.java#L83)
5. Now you will see the case of this topic

**Comment by sdeleuze** [comment] 2022-03-21 09:14
@LilPoppy Please update the sample and documentation to make it usable out of the box, for example by updating `docker-compose.yml` to run  MySQL and Redis with a simple `docker-compose up` or by adding a script that will set the various properties.

**Comment by sdeleuze** [comment] 2022-03-25 07:48
I tried and got the following error that seems unrelated with the issue you raised:
```
[INFO] DOCKER> [91mError: The reflection configuration file "/build/src/main/java/extra-reflect-config.json" does not exist.
[INFO] DOCKER> [91mcom.oracle.svm.core.util.UserError$UserException: The reflection configuration file "/build/src/main/java/extra-reflect-config.json" does not exist.
```
Could you please fix it?

**Comment by LilPoppy** [comment] 2022-03-25 14:03
> I tried and got the following error that seems unrelated with the issue you raised:
> 
> ```
> [INFO] DOCKER> [91mError: The reflection configuration file "/build/src/main/java/extra-reflect-config.json" does not exist.
> [INFO] DOCKER> [91mcom.oracle.svm.core.util.UserError$UserException: The reflection configuration file "/build/src/main/java/extra-reflect-config.json" does not exist.
> ```
> 
> Could you please fix it?

Hi @sdeleuze , you can add this [file](https://github.com/SpamanDev/StoreChain-Server/blob/main/src/main/java/extra-reflect-config.json) into the path, or remove this [line](https://github.com/SpamanDev/StoreChain-Server/blob/4e04cbe741a8222b55e43724bdd99c03e39f956a/pom.xml#L458) instead. This is another issue from GraalVM.

**Comment by sdeleuze** [comment] 2022-03-28 08:14
Another error `--trace-class-initialization=org.springframework.session.data.redis.RedisFlushMode`, I will make a last try if you fix it before closing this issue.

The error you see is not expected to happen with GraalVM 22.0 because inlining is enabled, so unless `-H:-InlineBeforeAnalysis` the reflective access is expected to be inlined and not requiring explicit reflection configuration.

**Comment by sdeleuze** [comment] 2022-03-31 08:33
Ok, I was able to reproduce after your latest comment and I can also reproduce with `@NativeHint(options = "--language:js")` added to the `webmvc-tomcat` sample. It seems `--language:js` also apply `-H:-InlineBeforeAnalysis` since this kind of error appear when inlining does not work. I will ping GraalVM team about that.

**Closed** 2022-04-05 09:40 UTC
Labels: type: bug, status: blocked
