### ISSUE TITLE
Build failed during Spring AOT test code generation: Unexpected problem processing bytes for class: NullPointerException

### ISSUE THREAD

**Issue by vietanh85** [spring-projects-experimental/spring-native#903] opened 2021-07-15 12:00 UTC
I followed this [guide](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#getting-started) to build native image but got this following error

```
 Build failed during Spring AOT test code generation: Unexpected problem processing bytes for class: NullPointerException
```

My JDK version:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```

- spring  version: 2.5.2
- sparing-native version: 0.10.1

Can any one help me to solve this?

Full logs:
```
[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.10.1:test-generate (test-generate) on project usee-starter-kit: Build failed during Spring AOT test code generation: Unexpected problem processing bytes for class: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.10.1:test-generate (test-generate) on project usee-starter-kit: Build failed during Spring AOT test code generation
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: Build failed during Spring AOT test code generation
    at org.springframework.aot.maven.TestGenerateMojo.execute (TestGenerateMojo.java:73)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalStateException: Unexpected problem processing bytes for class
    at org.springframework.nativex.type.ConstantPoolScanner.parseClass (ConstantPoolScanner.java:201)
    at org.springframework.nativex.type.ConstantPoolScanner.<init> (ConstantPoolScanner.java:139)
    at org.springframework.nativex.type.ConstantPoolScanner.<init> (ConstantPoolScanner.java:118)
    at org.springframework.nativex.support.Utils.scanClass (Utils.java:31)
    at org.springframework.nativex.type.TypeSystem.typenameOfClass (TypeSystem.java:1245)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:658)
    at java.util.stream.ReferencePipeline$7$1.accept (ReferencePipeline.java:274)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.springframework.nativex.type.TypeProcessor$2.toProcessTypes (TypeProcessor.java:467)
    at org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.toProcessTypesMatching (TypeProcessor.java:744)
    at org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.processTypes (TypeProcessor.java:715)
    at org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeConfigurationPropertiesHints (ConfigurationPropertiesHints.java:80)
    at org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeHints (ConfigurationPropertiesHints.java:65)
    at org.springframework.nativex.type.SpringConfiguration.<init> (SpringConfiguration.java:60)
    at org.springframework.nativex.type.TypeSystem.ensureSpringConfigurationDiscovered (TypeSystem.java:681)
    at org.springframework.nativex.type.TypeSystem.getAccessCheckers (TypeSystem.java:1066)
    at org.springframework.nativex.support.ReflectionHandler.addAccess (ReflectionHandler.java:130)
    at org.springframework.nativex.support.ReflectionHandler.addAccess (ReflectionHandler.java:90)
    at org.springframework.nativex.support.ReflectionHandler.registerWebApplicationTypeClasses (ReflectionHandler.java:64)
    at org.springframework.nativex.support.ReflectionHandler.register (ReflectionHandler.java:70)
    at org.springframework.nativex.support.SpringAnalyzer.analyze (SpringAnalyzer.java:86)
    at org.springframework.aot.nativex.ConfigurationContributor.contribute (ConfigurationContributor.java:70)
    at org.springframework.aot.BootstrapCodeGenerator.generate (BootstrapCodeGenerator.java:75)
    at org.springframework.aot.maven.TestGenerateMojo.execute (TestGenerateMojo.java:65)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at org.springframework.nativex.type.ConstantPoolScanner.parseClass (ConstantPoolScanner.java:188)
    at org.springframework.nativex.type.ConstantPoolScanner.<init> (ConstantPoolScanner.java:139)
    at org.springframework.nativex.type.ConstantPoolScanner.<init> (ConstantPoolScanner.java:118)
    at org.springframework.nativex.support.Utils.scanClass (Utils.java:31)
    at org.springframework.nativex.type.TypeSystem.typenameOfClass (TypeSystem.java:1245)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:658)
    at java.util.stream.ReferencePipeline$7$1.accept (ReferencePipeline.java:274)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1655)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.springframework.nativex.type.TypeProcessor$2.toProcessTypes (TypeProcessor.java:467)
    at org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.toProcessTypesMatching (TypeProcessor.java:744)
    at org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.processTypes (TypeProcessor.java:715)
    at org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeConfigurationPropertiesHints (ConfigurationPropertiesHints.java:80)
    at org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeHints (ConfigurationPropertiesHints.java:65)
    at org.springframework.nativex.type.SpringConfiguration.<init> (SpringConfiguration.java:60)
    at org.springframework.nativex.type.TypeSystem.ensureSpringConfigurationDiscovered (TypeSystem.java:681)
    at org.springframework.nativex.type.TypeSystem.getAccessCheckers (TypeSystem.java:1066)
    at org.springframework.nativex.support.ReflectionHandler.addAccess (ReflectionHandler.java:130)
    at org.springframework.nativex.support.ReflectionHandler.addAccess (ReflectionHandler.java:90)
    at org.springframework.nativex.support.ReflectionHandler.registerWebApplicationTypeClasses (ReflectionHandler.java:64)
    at org.springframework.nativex.support.ReflectionHandler.register (ReflectionHandler.java:70)
    at org.springframework.nativex.support.SpringAnalyzer.analyze (SpringAnalyzer.java:86)
    at org.springframework.aot.nativex.ConfigurationContributor.contribute (ConfigurationContributor.java:70)
    at org.springframework.aot.BootstrapCodeGenerator.generate (BootstrapCodeGenerator.java:75)
    at org.springframework.aot.maven.TestGenerateMojo.execute (TestGenerateMojo.java:65)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by ttddyy** [comment] 2021-07-18 08:51
Hi, 

Without repro project, I think it's difficult to get the real reason but based on the stack trace, I think [in `ConstantPoolScanner`, handling superclassname with `cpdata`](https://github.com/spring-projects-experimental/spring-native/blob/0.10.1/spring-aot/src/main/java/org/springframework/nativex/type/ConstantPoolScanner.java#L175-L190) is missing the case for `index=0`.

According to the ["JVM spec: Chapter 4. The class File Format"](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.1)

> "super_class"
>
>  For a class, the value of the super_class item either must be _**zero**_ or must be a valid index into the constant_pool table.
>  ...
>  If the value of the super_class item is _**zero**_, then this class file must represent the class Object, the only class or interface without a direct superclass. 
>  ...

So, `super_class(superclassname)` can be `0`.

Currently, the `cpdata` array is populated by [this for-loop](https://github.com/spring-projects-experimental/spring-native/blob/0.10.1/spring-aot/src/main/java/org/springframework/nativex/type/ConstantPoolScanner.java#L177-L182) which starts with `cpentry=1`
```java
for (int cpentry = 1; cpentry < cpsize; cpentry++) {
  boolean wasDoubleSlotItem = processConstantPoolEntry(cpentry);
  if (wasDoubleSlotItem) {
    cpentry++;
  }
}
```

Therefore, when `super_class` is `0`, `cpdata[0]` returns `null`.
Then, [the following code to obtain superclass name](https://github.com/spring-projects-experimental/spring-native/blob/0.10.1/spring-aot/src/main/java/org/springframework/nativex/type/ConstantPoolScanner.java#L188) unboxes `null`(`Integer`) to `int` which is throwing the reported NPE.

```java
classindex = ((Integer) cpdata[superclassname]);
```

cc @aclement

**Comment by sdeleuze** [comment] 2021-07-26 09:56
Closing it since no reproducer has be provided.

**Closed by sdeleuze** 2021-07-26 09:56 UTC
Labels: status: waiting-for-triage
