### ISSUE TITLE
Document Windows 10 support

### ISSUE THREAD

**Issue by ozkanpakdil** [spring-projects-experimental/spring-native#233] opened 2020-08-16 20:32 UTC
Hello Team
I was just trying to see if graalvm build works in spring and ran build.sh in commandlinerunner. first issue I got was native-image command not found. I tried

`export PATH=$PATH:/c/Program\ Files/GraalVM/graalvm-ce-java11-20.1.0/bin/
alias native-image="native-image.cmd"`

did not work, so I changed compile.sh and changed native-image to native-image.cmd but then I got this error

`ozkan@DESKTOP-NF90OD6 MINGW64 /d/tmp/spring-graalvm-native-samples/commandlinerunner
$ ./build.sh
=== Building commandlinerunner sample ===
Packaging commandlinerunner with Maven
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Unpacking commandlinerunner-0.0.1-SNAPSHOT.jar
Compiling commandlinerunner with GraalVM Version 20.1.0 (Java Version 11.0.7)
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 16: BOOT-INF\classes:BOOT-INF\lib:BOOT-INF\lib\jakarta.annotation-api-1.3.5.jar:BOOT-INF\lib\snakeyaml-1.26.jar:BOOT-INF\lib\spring-aop-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-beans-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-boot-2.3.1.RELEASE.jar:BOOT-INF\lib\spring-boot-autoconfigure-2.3.1.RELEASE.jar:BOOT-INF\lib\spring-boot-starter-2.3.1.RELEASE.jar:BOOT-INF\lib\spring-context-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-context-indexer-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-core-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-expression-5.2.7.RELEASE.jar:BOOT-INF\lib\spring-graalvm-native-0.7.1.jar:BOOT-INF\lib\spring-jcl-5.2.7.RELEASE.jar:
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.nio.file.Path.of(Path.java:147)
        at java.nio.file.Paths.get(Paths.java:69)
        at com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:50)
        at com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1416)
        at com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:233)
        at com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:104)
        at com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1365)
        at com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1581)
        at com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:1026)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1290)
`

I use git bash for windows, I also have openjdk 14 installed in my local. may be that error is related, anyway here is my mvn version

`$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3
Java version: 14.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\OpenJDK\jdk-14.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
`

btw I did build https://github.com/ozkanpakdil/quarkus-examples/tree/master/qute-test with graalvm in my local before. so I am sure graalvm can build exe in win10.

Feel free to ask if I am missing something 😄

**Comment by cmlonder** [comment] 2020-08-17 17:07
Path separator for windows is ";" but in this output, I can see it is shown as ":".  Not checked spring build scripts but you can try to use ";" instead of ":" where library paths are merged.

**Comment by aclement** [comment] 2020-08-18 04:42
Yeah, those build scripts aren't friendly to windows. The samples are gradually moving to maven which will work much better, applying the maven guidelines in docs (like described in https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-docs/src/main/asciidoc/feature.adoc ) would make that sample work. I hope to find some time to get testing on windows done.  In some other issues on here users have successully been using this project to build their Spring apps on windows, they skipped the samples and just applied the maven guidelines to their projects.

**Comment by aclement** [comment] 2020-08-18 04:55
Just to make it easier, this is the exact bit to paste into the commandlinerunner/pom.xml to build it via maven:
```
   <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.nativeimage</groupId>
                        <artifactId>native-image-maven-plugin</artifactId>
                        <version>20.1.0</version>
                        <configuration>
                            <mainClass>com.example.commandlinerunner.CommandlinerunnerApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```
and then `mvn -Pnative clean package` and run the resultant `com.example.commandlinerunner.CommandlinerunnerApplication` in the target folder.

**Comment by ozkanpakdil** [comment] 2020-08-18 09:23
first I got https://github.com/oracle/graal/issues/2525 error, then I removed openjdk from path and now I get 

`[ERROR] Failed to execute goal org.graalvm.nativeimage:native-image-maven-plugin:20.1.0:native-image (default) on project commandlinerunner: Image building on Java 11+ without native-image requires MAVEN_OPTS='--add-exports=java.base/jdk.internal.module=ALL-UNNAMED' -> [Help 1]`

Generally graalvm is problematic in windows I am aware of it.

**Comment by aclement** [comment] 2020-10-14 05:11
I can confirm I have now successfully built some of the samples on Windows 10. I used Graal 20.2 with Java 11 and running on the special terminal they recommend ("x64 Native Tools Command Prompt for VS 2017"). I used the maven snippet above (updated for Graal 20.2), then a `mvn -Pnative clean package` and it gave me a .exe file. I ran the commandlinerunner and webmvc-tomcat samples like this. They seemed to have a similar profile (image size/memory) as their linux/Mac counterparts. My colleague had issues with 'command line too long' (we think due to class path length in the command that gets run) - he was able to workaround that using the `subst` command workaround in https://stackoverflow.com/questions/8181098/the-command-line-is-too-long-in-java-project-with-maven/8211150

**Comment by aclement** [comment] 2020-10-14 05:11
For 0.9.0 let's get some Windows documentation in place.

**Comment by sdeleuze** [comment] 2021-01-05 09:10
I can now do some Windows 10 testing myself so I will take it from there.

**Closed** 2021-01-21 08:49 UTC
Labels: type: documentation

**Comment by sdeleuze** [comment] 2021-01-21 08:51
I have been able to do various tests on Windows and adapt the documentation accordingly. Notice that performances with buildpack + Docker are great on Windows thanks for [Docker WSL2 backend](https://docs.docker.com/docker-for-windows/wsl/), so only Mac provide suboptimal container-based build performances.
