### ISSUE TITLE
Add Support for ApplicationContextAware

### ISSUE THREAD

**Issue by goafabric** [spring-projects-experimental/spring-native#949] opened 2021-08-04 11:30 UTC
As mentioned in 
https://github.com/spring-projects-experimental/spring-native/issues/869,
ApplicationContextAware is currently not working

Imagine a class like:

--- cut ---
public class AuditJpaListener implements ApplicationContextAware {
    private static ApplicationContext context;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        context = applicationContext;
    }
----

The context will always be null.
As the related EntityListeners are not able to use Spring Beans in another way,
it would be nice if this will be fixed

**Comment by snicoll** [comment] 2021-08-14 05:46
I think this is probably a duplicate of #869. If entity listeners are not handled as spring beans, it is to be expected the callback is not called. Have you tried with a regular Spring bean? (i.e. `@Component`).

**Comment by goafabric** [comment] 2021-08-16 15:56
Nope neither is it a duplicate of 869, because i was explictly askes to raise this extra issue

2nd I tries @component … does also not work

**Comment by sdeleuze** [comment] 2021-08-17 15:09
I am surprised that `@Component` does not work, but let's check, could you please share your repro project?

**Comment by goafabric** [comment] 2021-08-18 07:20
@sdeleuze 
Yes sure .. here is the complete path to the class in Question:
https://github.com/goafabric/person-service/blob/develop/src/main/java/org/goafabric/personservice/persistence/audit/AuditJpaListener.java

This also needs the currently commented out TypeHint inside the Application class.

@Component had a very non deterministic behaviour when trying it out
But honestly .. in never really understood if @Component is meant to be Used on the EntityListener classes,
as these classes are / can normally not managed by Spring, afaik

Thx in advance

Andreas

**Comment by goafabric** [comment] 2021-08-19 08:33
Just for the sake of clarity .. @Component WOrks in JVM Mode
But in native mode, it inflicts the same behaviour as ApplicationContextAware.
Which means that the injected ApplicationContext is always null.
Injecting beans directly without the ApplicationContext, also leads to null Objects.

So i guess in Native Mode, Spring is not able to Manage the class ? .... Maybe this has to do with the Extra Reflection Hint that has to be set ?

**Comment by sdeleuze** [comment] 2021-09-27 08:27
`ApplicationContextAware` is already supported see 4b6b61c1b8faf9d8cfd72da78d82ecd9a4972082.

**Closed by sdeleuze** 2021-09-27 08:27 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by goafabric** [comment] 2021-11-05 09:52
sorry to say .. i don't know what was fixed and what not ...
but upgrading to 10.0.4 stills needs the Typehint for the EntityListener Class
 (//@TypeHint(types = AuditJpaListener.class)

And then inside the class, that is ApplicationContextAware, i still get the same Null Pointer as before, because the ApplationContext ist still null

**Comment by sdeleuze** [comment] 2021-11-28 14:33
I mean with `0.11`.
