### ISSUE TITLE
Spring AOT Plugin crashes in project with module-info.java

### ISSUE THREAD

**Issue by Nightloewe** [spring-projects-experimental/spring-native#1066] opened 2021-09-24 01:27 UTC
The Spring AOT Maven Plugin fails with the following error message when the project contains a `module-info.java`:

```
[INFO] Spring Native operating mode: native
[ERROR] java.lang.IllegalStateException: Unexpected problem processing bytes for class
[ERROR] [org.springframework.nativex.type.ConstantPoolScanner.parseClass(ConstantPoolScanner.java:201), org.springframework.nativex.type.ConstantPoolScanner.<init>(ConstantPoolScanner.java:139), org.springframework.nativex.type.ConstantPoolScanner.<init>(ConstantPoolScanner.java:118), org.springframework.nativex.support.Utils.scanClass(Utils.java:31), org.springframework.nativex.type.TypeSystem.typenameOfClass(TypeSystem.java:1465), java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195), java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655), java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658), java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274), java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655), java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484), java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474), java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150), java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173), java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234), java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497), org.springframework.nativex.type.TypeProcessor$2.toProcessTypes(TypeProcessor.java:467), org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.toProcessTypesMatching(TypeProcessor.java:744), org.springframework.nativex.type.TypeProcessor$TypeHintCreatingProcessor.processTypes(TypeProcessor.java:715), org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeConfigurationPropertiesHints(ConfigurationPropertiesHints.java:80), org.springframework.boot.context.properties.ConfigurationPropertiesHints.computeHints(ConfigurationPropertiesHints.java:65), org.springframework.nativex.type.SpringConfiguration.<init>(SpringConfiguration.java:60), org.springframework.nativex.type.TypeSystem.ensureSpringConfigurationDiscovered(TypeSystem.java:897), org.springframework.nativex.type.TypeSystem.getAccessCheckers(TypeSystem.java:1282), org.springframework.nativex.support.ReflectionHandler.addAccess(ReflectionHandler.java:130), org.springframework.nativex.support.ReflectionHandler.addAccess(ReflectionHandler.java:90), org.springframework.nativex.support.ReflectionHandler.register(ReflectionHandler.java:72), org.springframework.nativex.support.SpringAnalyzer.analyze(SpringAnalyzer.java:86), org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:70), org.springframework.aot.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:77), org.springframework.aot.maven.TestGenerateMojo.execute(TestGenerateMojo.java:65), org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156), org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117), org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81), org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56), org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305), org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192), org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105), org.apache.maven.cli.MavenCli.execute(MavenCli.java:957), org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289), org.apache.maven.cli.MavenCli.main(MavenCli.java:193), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282), org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225), org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406), org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)]
```

**Comment by sdeleuze** [comment] 2021-09-26 16:34
I tried but was not able to reproduce, could you please provide a repro project?

**Comment by aclement** [comment] 2021-09-28 04:24
I can take a look at this one Sebastien, I suspect i know what it'll be.

**Comment by sdeleuze** [comment] 2021-09-28 07:23
Ok thanks I assigned this one to you.

**Closed** 2021-10-04 01:31 UTC
Labels: type: bug, status: waiting-for-feedback
