### ISSUE TITLE
i use Visual Studio Community to build spring-boot:2.7 failure

### ISSUE THREAD

**Issue by huiji121** [spring-projects-experimental/spring-native#1741] opened 2022-12-23 09:28 UTC
<img width="744" alt="WeChat685f06314f5b0d18104ab347ebee72c9" src="https://user-images.githubusercontent.com/24616352/209309808-1e0e8af6-75b5-429d-9077-461d89e53077.png">

**Comment by huiji121** [comment] 2022-12-23 09:29
How can I solve this problem

**Comment by huiji121** [comment] 2022-12-26 02:57
springboot:2.7.7
aot:0.12.1

**Comment by wangliang181230** [comment] 2022-12-27 07:56
Downgrading springboot to version 2.7.5

**Comment by huiji121** [comment] 2022-12-28 02:19
think you

**Comment by sdeleuze** [comment] 2023-01-02 11:47
Duplicate of #1740.

**Closed by sdeleuze** 2023-01-02 11:47 UTC
Labels: status: duplicate
