### ISSUE TITLE
Spring boot 2.6.4 and mongo - reflection configuration missing for Query

### ISSUE THREAD

**Issue by lukaszpy** [spring-projects-experimental/spring-native#1564] opened 2022-03-31 09:36 UTC
Hello i'm getting : 
`Native reflection configuration for org.springframework.data.mongodb.core.query.Query is missing.`

my build gradle:

```import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.springframework.boot") version "2.6.4"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.6.10"
    kotlin("plugin.spring") version "1.6.10"
    id("org.springframework.experimental.aot") version "0.11.3"
}

group = "com.services.playit"

java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
  maven { url = uri("https://repo.spring.io/release") }
  mavenCentral()
}


extra["springCloudVersion"] = "2021.0.1"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-security")

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb-reactive")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")

    implementation("io.github.microutils:kotlin-logging:2.1.21")
    implementation("com.auth0:java-jwt:3.19.0")
    implementation("com.auth0:jwks-rsa:0.21.0")
    implementation("org.bouncycastle:bcprov-jdk15on:1.70")

    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}


tasks.getByName<org.springframework.boot.gradle.tasks.bundling.BootBuildImage>("bootBuildImage") {
    runImage = System.getenv("CUSTOM_REGISTRY_URL") + "/paketobuildpacks/run:tiny-cnb"
    builder = System.getenv("CUSTOM_REGISTRY_URL") + "/paketobuildpacks/builder:tiny"
    environment = mapOf(
            "BP_NATIVE_IMAGE"                       to "true",
            "BP_NATIVE_IMAGE_BUILD_ARGUMENTS"       to "--enable-all-security-services"
	)

    isPublish = true

    docker {
        host = "unix:///var/run/docker.sock"

        builderRegistry {
            username = System.getenv("CUSTOM_REGISTRY_USER")
            password = System.getenv("CUSTOM_REGISTRY_PASS")
            url = System.getenv("CUSTOM_REGISTRY_URL")
        }

        publishRegistry {
            username = "gitlab-ci-token"
            password = System.getenv("CI_JOB_TOKEN")
            url = System.getenv("CI_REGISTRY")
        }
    }
}```

**Comment by mhalbritter** [comment] 2022-03-31 12:25
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by lukaszpy** [comment] 2022-03-31 12:27
@mhalbritter got it working by changing spring repository interface into concrete class with my implementation. 
But now I have problem with DB model class " Unresolved class"

**Comment by mhalbritter** [comment] 2022-03-31 13:26
Nice. Please provide a minimal sample (something that we can unzip or git clone, build, and deploy), then i can look into it.

**Comment by spring-projects-issues** [comment] 2022-04-07 13:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-04-14 13:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-04-14 13:28 UTC
Labels: status: waiting-for-triage, status: feedback-reminder, status: waiting-for-feedback
