### ISSUE TITLE
Spring native resources

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-native#1591] opened 2022-04-19 16:41 UTC
hi

spring boot 2.6.6, spring native  0.11.4, graalvm 22 (java 17), kotlin 1.6.20

file (data.txt) place it in resource folder
 
```
@NativeHint(
    types = [TypeHint(types = [Person::class])],
    resources = [ResourceHint(patterns = ["data.txt"], isBundle = true)]
)
@SpringBootApplication
class SpringNativeDemoApplication


val log = LoggerFactory.getLogger("spring-native-demo")

val applicationOnReady = ApplicationListener<ApplicationStartedEvent> {
    val file = ClassPathResource("data.txt").file.readText()
    log.info("load data from resource >>>> \n[$file]")
}


fun route() = beans {
    bean {
        coRouter {
            GET("") { ok().bodyValueAndAwait("salam") }
            GET("/{id}") { ok().bodyValueAndAwait(it.pathVariable("id")) }
            GET("/data/json") { ok().bodyValueAndAwait(Person(id = 1, name = "halim")) }
        }
    }
}

fun main() {
    runApplication<SpringNativeDemoApplication> {
        addInitializers(route())
        addListeners(applicationOnReady)
    }
}
```

when create native executable with graalvm and launch it, 2 issue happen

1. class Person not serialize in client side  ({} empty object receive)
2.
```
2022-04-19 17:35:37.151  INFO 7644 --- [           main] o.s.nativex.NativeListener               : AOT mode enabled

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

2022-04-19 17:35:37.155  INFO 7644 --- [           main] o.s.boot.SpringApplication               : Starting application using Java 17.0.2 on Ghost with PID 7644 (started by halim in /home/halim/Software/spring-native-demo/build/native/nativeCompile)
2022-04-19 17:35:37.155  INFO 7644 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to 1 default profile: "default"
2022-04-19 17:35:37.178  INFO 7644 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 9999
2022-04-19 17:35:37.178  INFO 7644 --- [           main] o.s.boot.SpringApplication               : Started application in 0.052 seconds (JVM running for 0.053)
2022-04-19 17:35:37.179 ERROR 7644 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.io.FileNotFoundException: class path resource [data.txt] cannot be resolved to absolute file path because it does not reside in the file system: resource:data.txt
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[na:na]
```

**Comment by mhalbritter** [comment] 2022-04-20 07:46
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-04-27 07:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-05-04 07:51
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-05-04 07:51 UTC
Labels: status: waiting-for-triage, status: feedback-reminder, status: waiting-for-feedback
