### ISSUE TITLE
"The command line is too long." error on Windows when running native tests

### ISSUE THREAD

**Issue by mstine** [spring-projects-experimental/spring-native#970] opened 2021-08-12 15:06 UTC
Environment:

- Windows 7
- GraalVM Enterprise 21.2.0 - Java 11
- Spring Native 0.10.1

Command:

`mvn -Pnative test`

Output (snippet - full output contains proprietary information):

```
-H:Name=native-tests.exe org.graalvm.junit.platform.NativeImageJUnitLauncher
The command line is too long.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.594 s
[INFO] Finished at: 2021-08-12T09:41:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.1:test (test-native) on project graalvm-native-image-functional-tests
```

It appears that https://github.com/oracle/graal/commit/7baf86977f56afe2dfcd450a082a4f0f673195f8 should address this issue, so it's not clear to me if the problem is something on my end.

**Comment by ch4mpy** [comment] 2021-08-12 18:12
I think there is an issue opend for that on Graalvm side: https://github.com/oracle/graal/issues/2995

Waiting this to be fixed, I have two different work-arounds
- build on Linux env (I chose dual boot, but WSL should work just fine)
- under Windows, instead of using `native-image-maven-plugin` work with `spring-boot-maven-plugin`:
``` xml
						<plugin>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-maven-plugin</artifactId>
							<configuration>
								<excludes>
									<exclude>
										<groupId>org.projectlombok</groupId>
										<artifactId>lombok</artifactId>
									</exclude>
								</excludes>
								<classifier></classifier>
							</configuration>
							<executions>
								<execution>
									<id>build-image</id>
									<goals>
										<goal>build-image</goal>
									</goals>
									<configuration>
										<image>
											<builder>paketobuildpacks/builder:tiny</builder>
											<env>
												<BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
												<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
													-H:+ReportExceptionStackTraces
													--enable-https
													-H:+InlineBeforeAnalysis
													--initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder
													--verbose
												</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
											</env>
											<pullPolicy>IF_NOT_PRESENT</pullPolicy>
										</image>
									</configuration>
								</execution>
							</executions>
						</plugin>
				<plugin>
					<groupId>org.springframework.experimental</groupId>
					<artifactId>spring-aot-maven-plugin</artifactId>
					<version>${spring-native.version}</version>
					<configuration>
						<removeXmlSupport>true</removeXmlSupport>
						<removeSpelSupport>false</removeSpelSupport>
						<removeYamlSupport>true</removeYamlSupport>
						<removeJmxSupport>true</removeJmxSupport>
						<removeUnusedConfig>false</removeUnusedConfig>
					</configuration>
					<executions>
						<execution>
							<id>test-generate</id>
							<goals>
								<goal>test-generate</goal>
							</goals>
						</execution>
						<execution>
							<id>generate</id>
							<goals>
								<goal>generate</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
```

**Comment by mstine** [comment] 2021-08-12 19:35
Oh, interesting. I had not seen the separate issue for the Maven plugin. So this is likely not a Spring Native problem.

Unfortunately, neither of those options are going to be viable in the environment I'm supporting.

**Comment by wxq1990** [comment] 2021-08-13 08:42
I have same error with gradle
Environment:

Windows 10
GraalVM Enterprise 21.2.0 - Java 11
Spring Native 0.10.2
Command:

.\gradlew nativeBuild

Output (snippet - full output contains proprietary information):
`> Task :nativeBuild FAILED
The command line is too long.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeBuild'.
> Process 'command 'D:\sdk\java\graalvm11\bin\native-image.cmd'' finished with non-zero exit value 1
`

**Comment by snicoll** [comment] 2021-08-14 05:43
Yeah, there's nothing we can do here. Closing as a duplicate of https://github.com/oracle/graal/issues/2995

**Closed by snicoll** 2021-08-14 05:43 UTC
Labels: status: waiting-for-triage

**Comment by ch4mpy** [comment] 2021-08-15 02:03
@snicoll this oracle/graal#2995 hasn't moved since november 2020. Given it's a major issue for building spring-boot native images on Windows, it could be usefull that Spring members at least comment on it.

Pulling docker images which download Graalvm at each build is not acceptable with my internet access.

**Comment by mstine** [comment] 2021-08-17 13:50
@snicoll agreed. Our environment won't support running tests this way. We need to use the native build tools on Windows workstations, so it would be useful to vote this up with the GraalVM team.

**Comment by snicoll** [comment] 2021-08-17 13:53
@ch4mpy @mstine we don't need to comment on it. We're working on this, amongst other things, with the Graal team directly.
