### ISSUE TITLE
Spring Cloud Stream fail to crate AOT transformation

### ISSUE THREAD

**Issue by Hajosman** [spring-projects-experimental/spring-native#1429] opened 2022-01-07 17:41 UTC
Hey,

I am trying to implement a project that uses Spring-Cloud-Stram RabbitMQ to exchange messages and connects to a Spring-Cloud server. this works without problems when I run it in the JVM, but does not work when I run it as Native. Both mvn spring-aot:generate and mvn clean -Pnative -DskipTests package fail 

technologies used:
spring-boot: 2.6.2
spring-native:0.11.1
spring-cloud: 2021.0.0
spring-integration: 5.5.7
spring-cloud-starter-stream-rabbit

Used pom.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>myDeno</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.2</version>
		<relativePath/> 
	</parent>

	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2021.0.0</spring-cloud.version>
		<repackage.classifier/>
		<spring-native.version>0.11.1</spring-native.version>
	</properties>

	<dependencies>
		</dependency>
				<dependency>
					<groupId>org.springframework.cloud</groupId>
					<artifactId>spring-cloud-stream</artifactId>
				</dependency>
				<dependency>
					<groupId>org.springframework.cloud</groupId>
					<artifactId>spring-cloud-starter-stream-rabbit</artifactId>
				</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.experimental</groupId>
			<artifactId>spring-native</artifactId>
			<version>${spring-native.version}</version>
		</dependency>
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.0.Final</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.12.5</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>RELEASE</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.11</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.12.5</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.12.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.9</version>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

I get the following error message: 
[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.11.1:generate (generate) on project demo: Build failed during Spring AOT code generation: Unable to execute mojo: Compilation failure:
[ERROR] /C:/Users/hajosman/Downloads/demo/demo/target/generated-sources/spring-aot/src/main/java/org/springframework/cloud/stream/binding/ContextBootstrapInitializer.java:[43,63] ')' expected
[ERROR] /C:/Users/hajosman/Downloads/demo/demo/target/generated-sources/spring-aot/src/main/java/org/springframework/cloud/stream/binding/ContextBootstrapInitializer.java:[43,114] ';' expected
 
it seems that the AOT compiler produces wrong syntax.
The place where an incorrect syntax was produced looks like this:

   public static void registerBindableProxyFactory(DefaultListableBeanFactory beanFactory) {
        BeanDefinitionRegistrar.of("com.example.demo.model.stream.RuntimeQueueProcessor", BindableProxyFactory.class).withConstructor(Class.class)
            .instanceSupplier((instanceContext) -> {
              BindableProxyFactory bean = instanceContext.create(beanFactory, (attributes) -> new BindableProxyFactory(attributes.get(0)));
              instanceContext.field("namespace", String.class)
                  .invoke(beanFactory, (attributes) -> {
                    Field namespaceField = ReflectionUtils.findField(AbstractBindableProxyFactory.class, "namespace", String.class);
                    ReflectionUtils.makeAccessible(namespaceField);
                    ReflectionUtils.setField(namespaceField, bean, attributes.get(0));
                  });
                  return bean;
                }).customize((bd) -> ConstructorArgumentValues argumentValues = bd.getConstructorArgumentValues()).register(beanFactory);
          }

where the last line is syntactically incorrect (customize((bd) -> ConstructorArgumentValues argumentValues = bd.getConstructorArgumentValues()).register(beanFactory);
          })

then i added the following hint:
@AotProxyHint(types =com.example.demo.model.stream.RuntimeQueueProcessor.class)
Which didn't change anything though.

Excerpt from RuntimeQueueProcessor: 
public interface RuntimeQueueProcessor {

    /**
     * The configuration of the Rabbit Server is done in the respective applications.
     * application.yml. Queue-name is the addressed microservice.
     * <queue-name>_IN/OUT specifies whether the queue function enqueue or dequeue.
     * is addressed.
     */

    @Output(LOAD_xy_IN)
    MessageChannel loadxyIn();

    @Input(LOAD_xy_OUT)
    SubscribableChannel loadxyOut();

i then tried to compile the code with the new AOT compiler (0.11.2-SNAPSHOT). after that i got the following:
[ERROR] Failed to execute goal org.springframework.experimental:spring-aot-maven-plugin:0.11.2-SNAPSHOT:generate (generate) on project demo: Build failed during Spring AOT code generation: Unable to execute mojo: Compilation failure:
[ERROR] /C:/Users/hajosman/Downloads/demo/demo/target/generated-sources/spring-aot/src/main/java/org/springframework/cloud/stream/config/ContextBootstrapInitializer.java:[72,111] org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration.BindersH
ealthContributor has private access in org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration
[ERROR] /C:/Users/hajosman/Downloads/demo/demo/target/generated-sources/spring-aot/src/main/java/org/springframework/cloud/stream/config/ContextBootstrapInitializer.java:[78,253] org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration.BindersH
ealthContributor has private access in org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration

then i added the following hint:
@TypeHint(typeNames = "org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration.BindersHealthContributor")
Which didn't change anything though.
can someone help me with this

**Comment by snicoll** [comment] 2022-01-11 14:33
Thanks for the report. This is a duplicate of #1403. As for `BindersHealthIndicatorAutoConfiguration` this is a duplicate of https://github.com/spring-cloud/spring-cloud-stream/issues/2254. 

Thanks for trying the snapshot but if the exception goes away, please edit your description as it is very long and quite hard to grasp.

Please note that Spring Cloud Stream isn't supported at the moment.

**Closed by snicoll** 2022-01-11 14:33 UTC
Labels: status: waiting-for-triage
