### ISSUE TITLE
How to add pagehelper-spring-boot-starter?

### ISSUE THREAD

**Issue by wghdir** [spring-projects-experimental/spring-native#1751] opened 2023-02-14 09:19 UTC
add  
      <dependency>
            <groupId>com.github.pagehelper</groupId>
            <artifactId>pagehelper-spring-boot-starter</artifactId>
            <version>1.4.6</version>
        </dependency>
@TypeHint(types = {PageHelper.class})

but run error
### Error opening session.  
Cause: org.apache.ibatis.plugin.PluginException: Could not find method on interface org.apache.ibatis.executor.Executor named query. 
Cause: java.lang.NoSuchMethodException: org.apache.ibatis.executor.Executor.query(org.apache.ibatis.mapping.MappedStatement, java.lang.Object, org.apache.ibatis.session.RowBounds, org.apache.ibatis.session.ResultHandler)

**Comment by sdeleuze** [comment] 2023-02-15 16:12
Spring Native is now superseded by Spring Boot 3 official native support, see [the related reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html) for more details.

As a consequence, I am closing this issue, and recommend trying your use case with latest Spring Boot 3 version.

The starter you try to use seems to be a community maitained one so the issue is probably to open on community project side not Spring.

**Closed as not planned by sdeleuze** 2023-02-15 16:12 UTC
Labels: status: declined
