### ISSUE TITLE
How to work with @Configurations guarded by @Profile

### ISSUE THREAD

**Issue by cylab** [spring-projects-experimental/spring-native#1436] opened 2022-01-10 15:37 UTC
I have a configuration class that is conditional via @Profile. This does not seem to be supported at run-time. I tried to specify "-Dspring.profiles.active=kubernetes" as BP_NATIVE_IMAGE_BUILD_ARGUMENTS to only activate this in builds for deployments, but this did not help.

What alternatives do I have?
```
@Configuration
@Profile("kubernetes")
class SQSConfig() {

    @PostConstruct
    fun postConstruct() {
        logger.info("Created SQSConfig")
        logger.info("EVENT_QUEUE_URL: >${System.getenv("EVENT_QUEUE_URL")}<")
    }

    @SqsListener("\${EVENT_QUEUE_URL}", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
    fun receiveEvent(@NotificationMessage eventRaw: String, @NotificationSubject subject: String) {
        logger.info { "Received SNS/SQS event $subject: $eventRaw" }
    }

    companion object : KLogging()
}
```

**Comment by sdeleuze** [comment] 2022-01-10 16:53
I think this is a duplicate of #1411.

**Closed by sdeleuze** 2022-01-10 16:53 UTC
Labels: status: waiting-for-triage

**Comment by cylab** [comment] 2022-01-11 08:55
Thanks. I think the info on the linked issue will help me out.

Just out of curiosity: what is actually preventing @Profile and @Conditional annotations from working in spring native? Is there a fundamental hurdle or is it a matter of time and priority? From my naive perspective, I would have guessed, the conditions "just" have to be baked into the generated BeanFactories, so they can be evaluated at runtime...

**Comment by sdeleuze** [comment] 2022-01-11 10:15
They work but currently they are evaluated at build time, see https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#spring-aot for more details. We may provide a more flexible system later.
