### ISSUE TITLE
Kotlin Data Class serialization empty

### ISSUE THREAD

**Issue by halimpuckjava** [spring-projects-experimental/spring-native#944] opened 2021-07-30 14:01 UTC
hi

kotlin 1.5.21, spring native 0.10.2-snapshot, spring boot 2.5.3: 

when generate native executable (native build) and launch it, each kotlin data class send to client is empty json object !!!, however with jar exe the client receive each data class correctly

**Comment by sdeleuze** [comment] 2021-07-30 20:56
Did you add hints like in https://github.com/spring-projects-experimental/spring-native/blob/main/samples/webclient/src/main/java/com/example/webclient/WebClientApplication.java#L7? For such use case, this is needed.

Instead you can also use Kotlin Serialization instead Jackson, it should not require reflection config, but I have note tried it on native yet.

Please share a reproducer if you need more help.

**Comment by halimpuckjava** [comment] 2021-08-01 13:03
```
@SpringBootApplication
class DemoApplication

data class Person(val id: Int, val name: String)

val onReady = ApplicationListener<ApplicationReadyEvent> { println("server is ready") }

val routing = beans {
	bean {
		coRouter {
			GET("/json") { ok().bodyValueAndAwait(Person(1, "person")) }
			GET("") { ok().bodyValueAndAwait("hi") }
			GET("/msg/{msg}") { ok().bodyValueAndAwait(it.pathVariable("msg").uppercase()) }
		}
	}
}

fun main() {
	runApplication<DemoApplication> {
		addInitializers(routing)
		addListeners(onReady)
	}
}
```

**Comment by halimpuckjava** [comment] 2021-08-03 09:56
hi

when add  
```
@TypeHint(types = [Person::class])
```
its wotk fine and each data class serialize correctly, i try to move from jackson -> kotlinx serialization and remove @TypeHInt annotation but its not work, 

so what @TypeHint do in serialization phase ??

**Comment by sdeleuze** [comment] 2021-08-17 15:13
Please share a downloadable project or a repository with the project using kotlinx-serialization where `@TypeHint` is still needed.

**Comment by spring-projects-issues** [comment] 2021-08-24 15:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-08-31 15:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-08-31 15:14 UTC
Labels: status: waiting-for-triage, status: feedback-reminder, status: waiting-for-feedback
