### ISSUE TITLE
Gradle build fail with spring-boot-starter-data-rest

### ISSUE THREAD

**Issue by Coderdreams** [spring-projects-experimental/spring-native#776] opened 2021-05-12 07:54 UTC
Compilation returns this error even when passing the environment parameter for verify=false:

```
~/projects/springbootdemo/demo$ ./gradlew -Dspring.native.verify=false bootBuildImage
> Task :generateAot FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateAot'.
> ERROR: in 'org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration' these methods are directly invoking methods marked @Bean: [pageableResolver, sortResolver] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection. If you are confident this is not going to affect your application, you may turn this check off using -Dspring.native.verify=false.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 2 executed, 1 up-to-date
```
build.gradle:

```
plugins {
	id 'org.springframework.boot' version '2.4.5'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'org.springframework.experimental.aot' version '0.9.2'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	maven { url 'https://repo.spring.io/release' }
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-rest'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	/*  implementation 'org.springframework.boot:spring-boot-starter'
  	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	  */
}

test {
	useJUnitPlatform()
}

bootBuildImage {
	builder = 'paketobuildpacks/builder:tiny'
	environment = ['BP_NATIVE_IMAGE': 'true']
}

```

Java version:

```
$ java --version
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

**Comment by sdeleuze** [comment] 2021-05-12 08:27
Likely a duplicate of #770 fixed on `0.10.0-SNAPSHOT`, verify should be set at Spring AOT Grade configuration level ([see related documentation](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/#spring-aot-gradle)), not via command line properties anymore.

**Closed by sdeleuze** 2021-05-12 08:27 UTC
Labels: status: waiting-for-triage
