### ISSUE TITLE
AuditingEntityListener is not working with spring-native

### ISSUE THREAD

**Issue by venkataklagisetty** [spring-projects-experimental/spring-native#1040] opened 2021-09-17 21:27 UTC
In my application, created and lastupdate userID and datetimestamp kept in an abstract class 
and then the ORM class of a table is inheriting above class.
Everything is working good.
as soon as I added spring-native dependency and required plugins of it, started getting exception saying "createddatetime" cannot be null.

providing below the abstract class from my project
@MappedSuperclass
@Data
@EntityListeners(value = AuditingEntityListener.class)
public abstract class AuditEntity {

    @Column(name = "CreateTimestamp", nullable = false, updatable = false)
    @JsonIgnore
    @CreatedDate
    private OffsetDateTime createTimestamp;

    @Column(name = "CreateUserID", length = 8, nullable = false, updatable = false)
    @JsonIgnore
    @CreatedBy
    private String createUserId;

    @Column(name = "LastUpdateTimestamp", nullable = false)
    @JsonIgnore
    @Version
    private OffsetDateTime lastUpdateTimestamp;

    @Column(name = "LastUpdateUserID", length = 8, nullable = false)
    @JsonIgnore
    @LastModifiedBy
    private String lastUpdateUserId;

its been working from long back ,but now with addition of spring-native above fields seemed not mapped any values nor executed

**Comment by venkataklagisetty** [comment] 2021-09-17 21:55
I just came to know while reading other issues.
below issue seems to be same.
https://github.com/spring-projects-experimental/spring-native/issues/869

Please guide me on it

**Comment by snicoll** [comment] 2021-09-20 15:12
Duplicate of #869.

**Closed by snicoll** 2021-09-20 15:12 UTC
Labels: status: waiting-for-triage
