### ISSUE TITLE
Problem with building native image for docker

### ISSUE THREAD

**Issue by hehor** [spring-projects-experimental/spring-native#1575] opened 2022-04-07 06:09 UTC
Builder: _Gradle_
_id 'org.springframework.boot'            version '2.6.6'_
 _id 'org.springframework.experimental.aot' version '0.11.4'_

I'm using the next configuration to build native image: 
```
bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    environment = [
            "BP_NATIVE_IMAGE" : "true",
            //"BP_NATIVE_IMAGE_BUILD_ARGUMENTS" : "--initialize-at-run-time=com.google.common.jimfs.SystemJimfsFileSystemProvider"
    ]
}
```
When I try to build native image I've got this error: 
`Error: Classes that should be initialized at run time got initialized during image building:
 com.google.common.jimfs.SystemJimfsFileSystemProvider was unintentionally initialized at build time. To see why com.google.common.jimfs.SystemJimfsFileSystemProvider got initialized use --trace-class-initialization=com.google.common.jimfs.SystemJimfsFileSystemProvider`

Also I was trying to add this argument _--initialize-at-run-time=com.google.common.jimfs.SystemJimfsFileSystemProvider_
but then I've got another error: 
`Error: The class com.google.common.jimfs.SystemJimfsFileSystemProvider has already been initialized (from the command line with 'com.google.common.jimfs.SystemJimfsFileSystemProvider'); it is too late to register com.google.common.jimfs.SystemJimfsFileSystemProvider for build-time initialization. To see why com.google.common.jimfs.SystemJimfsFileSystemProvider got initialized use --trace-class-initialization=com.google.common.jimfs.SystemJimfsFileSystemProvider`

**Comment by mhalbritter** [comment] 2022-04-07 07:20
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-04-14 07:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-04-21 07:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-04-21 07:23 UTC
Labels: status: waiting-for-triage, status: feedback-reminder, status: waiting-for-feedback
